### ISSUE TITLE
this gem supports model schema and body param type ?

### ISSUE THREAD

**Issue by chebyte** [ruby-grape/grape-swagger#101]
hi there I was seeing the code but seems that this gem doesnt support models and body param type, this is correct? I need that swagger-ui shows model schema and body param like this screenshot

![captura de pantalla 2014-04-08 a la s 18 05 12](https://cloud.githubusercontent.com/assets/20957/2649334/cf546b6a-bf61-11e3-89c4-e632e51e9406.png)

I have some way to do that with this gem?

thanks for advance

**Comment by zuk** [comment]
Ran into this issue with the GitHub version of grape (0.12.0) + grape_swagger. Seeing swagger JSON responses like this:

```
"apis": [
        {
            "path": "/foo/bar(.json)",
            "operations": [
                {
                    "method": "POST",
                    "parameters": [
                        {
                            "paramType": "form",
                            "name": "alpha",
                            "type": "string",
                            "required": true,
                            "allowMultiple": false
                        },
                        {
                            "paramType": "form",
                            "name": "beta",
                            "type": "string",
                            "required": false,
                        },
                        {
                            "paramType": "body",
                            "name": "gamma",
                            "type": "[Symbol]",
                            "required": false,
                            "allowMultiple": false
                        }
```

Note that the last parameter's paramType is `body` whereas the other ones are `form`.

The grape params block looks like this:

```
          requires :alpha, type: String
          optional :beta, type: Symbol
          optional :gamma, type: Array[Symbol]
```

The `type: Array[Symbol]` probably has something to do with this, but the same endpoint's swagger works as expected if I change it from `post` to `get`.

**Comment by zuk** [comment]
Never mind looks like I wasn't using the grape-swagger version I thought I was. Changing the param line to `optional :gamma, type: Array[Symbol], documentation: { param_type: 'form' }` did the trick.

**Comment by LeFnord** [comment]
impmented in actual versions
