### ISSUE TITLE
API basePath is coming back with port

### ISSUE THREAD

**Issue by ruprict** [ruby-grape/grape-swagger#107]
I am trying to serve the docs from a relative path for an app using HTTPS.  The Swagger JSON returns something like 

```
{
  "apiVersion":"v1",
  "swaggerVersion":"1.2",
  "resourcePath":"",
  "apis":[{
    "path":"/auth/user.{format}",
    "operations":[{
      "produces":["application/xml","application/json", "application/vnd.api+json","text/plain"],
      "notes":"",
      "summary":"",
      "nickname":"GET-auth-user---format-",
      "httpMethod":"GET",
      "parameters":[]
     }
  ]}],
  "basePath":"https://accounts.kyck.dev:80/api"}
```

`https` and port 80 are in direct conflict.  I have tried various options with `add_swagger_documentation`, including `include_base_url: false` and `root_base_path: false`

Not sure what I am doing wrong, but would love some help.

**Comment by dskecse** [comment]
As @dm1try states in a referenced pull request, since `https` and port `80` are in direct conflict, it seems like a configuration problem, so there is nothing unexpected in the gem's behaviour.

**Comment by LeFnord** [comment]
solved in actual versions
