### ISSUE TITLE
Support for grape version cascading

### ISSUE THREAD

**Issue by wyattisimo** [ruby-grape/grape-swagger#146]
If I mount my v1 endpoints like so:

``` ruby
module API::V1
  class Root < Grape::API
    version ['v2', 'v1'], using: :path

    mount API::V1::Places
    mount API::V1::Users

    add_swagger_documentation api_version: 'v1', mount_path: '/docs'
  end
end
```

...and mount my v2 endpoints like so:

``` ruby
module API::V2
  class Root < Grape::API
    version 'v2', using: :path, cascade: true

    mount API::V2::Users

    add_swagger_documentation api_version: 'v2', mount_path: '/docs'
  end
end
```

...then grape-swagger should understand the version cascading and include the `API::V1::Places` endpoints in the v2 docs. Currently, grape-swagger only reads the endpoints that are explicitly mounted in the module in which it is defined.

**Comment by florrain** [comment]
:+1:

**Comment by skwp** [comment]
Has anyone come up with a good solution for mounting multiple api versions on one swagger doc endpoint?

**Comment by brodock** [comment]
:+1:

**Comment by johnnygoodman** [comment]
+1

**Comment by przbadu** [comment]
:+1:

**Comment by LeFnord** [comment]
solved in actual versions

**Comment by al** [comment]
> ...then grape-swagger should understand the version cascading and include the API::V1::Places endpoints in the v2 docs. Currently, grape-swagger only reads the endpoints that are explicitly mounted in the module in which it is defined.

> solved in actual versions

Can anyone confirm that this is actually solved? (And if it is, maybe point to an example.)
