### ISSUE TITLE
swagger_doc.json returns wrong swagger doc urls

### ISSUE THREAD

**Issue by orbanbotond** [ruby-grape/grape-swagger#150]
See the description here:

http://stackoverflow.com/questions/25772229/swagger-doc-json-returns-wrong-swagger-doc-urls/25782328#25782328

It seems that since the version 0.7.2 the url_base get lost...

```
#0.7.2
:path => "#{url_base}/#{local_route}#{url_format}",

#0.8
path: "/#{local_route}#{url_format}",
```

**Comment by boomshadow** [comment]
I'm using ReDoc to view Swagger output. It was continually showing my endpoints as:

    http://127.0.0.1:9292undefined/v1/list

The only way to fix this was to specifically define the base_path, even though I'm not adding it:

    add_swagger_documentation \
        base_path: '/',
        add_base_path: false

**Comment by LeFnord** [comment]
@boomshadow … which version of grape-swagger you are using?
this is an issue of the old one, but the `add_base_path` assumes you are using > 0.21.x,
can you clarify it, and if it is version > 0.21.x, can you open an issue, thanks

**Comment by boomshadow** [comment]
@LeFnord ah, I missed that this was for the older version. Yes, I'm using 0.23.0. I'll open a new issue. Thanks for that.
