### ISSUE TITLE
Bad field for group parameters' name with type Array

### ISSUE THREAD

**Issue by nono** [ruby-grape/grape-swagger#160]
Hi,

this is the follow-up of #91. The following example doesn't work as expected:

``` ruby
params do
  optional :preferences, type: Array do
    requires :key
    requires :value
  end
end
```

Swagger-ui uses this to generate `preferences[key]=foo&preferences[value]=bar`, as if preferences was an hash and not array. I don't understand in the swagger spec how we are supposed to handle, so I can't write a failing spec. Sorry!

**Comment by u2** [comment]
#221 
What about the params `required`, dependent on `array`?

**Comment by LeFnord** [comment]
solved in actual versions
