### ISSUE TITLE
Endpoint authorization can no longer be passed in new Grape.

### ISSUE THREAD

**Issue by antek-drzewiecki** [ruby-grape/grape-swagger#177]
Grape introduces a new DSL https://github.com/intridea/grape/pull/757. This replaces the desc hash with a strict DSL. 

This no longer allows the authorization option to be passed to grape-swagger like defined in [Operations](https://github.com/swagger-api/swagger-spec/blob/master/schemas/v1.2/operationObject.json).

```
desc 'endpoint' , {
   authorizations: { oauth2: [{ scope: 'public' }] }
} 
```

No longer yields in :

```
operations: [ {
  authorizations: {
     oauth2: [ { scope: "public"} ] 
  }
}]
```

A way could to achieve this is to read the desc `headers`. Check if an Authorization header is defined.  The only problem is to define the authorization type (oauth, basic) and optional scopes.

**Comment by antek-drzewiecki** [comment]
Ill try to make a PR compatible with 0.10.x . Due time constrains please give me a week to set everything up ;)

**Comment by calfzhou** [comment]
+1

**Comment by LeFnord** [comment]
solved in actual versions
