### ISSUE TITLE
Converting :values range to enum

### ISSUE THREAD

**Issue by azhi** [ruby-grape/grape-swagger#235]
Exctacted from #233 and #234

Converting :values ranges to enums (arrays) in docs might not be the best idea.
It may lead to poor performance and huge JSON docs in case of large ranges.

I think the proper solution would be not to convert ranges to enums at all. However, this feature was in the release and some people might be using it.

Also we could try some dirty hack like convert to an array only if Range#size is less then some amount (say, 50). But that seems very odd to me.

**Comment by dblock** [comment]
This has been discussed and is definitely a problem, I'd appreciate a PR/fix.

**Comment by u2** [comment]
So, any good idea?

**Comment by u2** [comment]
#259

**Comment by vbalazs** [comment]
@LeFnord can we close this issue? As far as I can see it has been fixed with the PR in the previous comment.

**Comment by LeFnord** [comment]
think yes, in the master (OAPI2.0) the implementation is similar
what did you think @dblock?

**Comment by dblock** [comment]
I have no opinions here, do your thing :)
