### ISSUE TITLE
How to specify default status code?

### ISSUE THREAD

**Issue by Fryie** [ruby-grape/grape-swagger#236]
Apologies if I missed this, but I haven't found out how to specify the default response code of my endpoint. In fact, in Swagger UI I see "Response Class (Status )", with the Status clearly missing.

I know that I can add the http_codes options, but I'd like to use that just for exceptional conditions due to the way it's displayed.

Basically, I want to do this: http://petstore.swagger.io/#!/store/placeOrder

**Comment by dblock** [comment]
Can you dig up where this appears in the swagger JSON in that example you linked? We can extrapolate from there.

**Comment by dblock** [comment]
I should have looked myself :)

![screen shot 2015-03-19 at 4 24 55 pm](https://cloud.githubusercontent.com/assets/542335/6740199/8571c300-ce54-11e4-99c6-0ccb97de7984.png)

I think it's the first one from `responses`, which is customized via `http_codes`:

```
get '/', http_codes: [
  [200, 'Ok', Entities::Client],
  [400, "Invalid parameter entry"]
] do
  ...
end
```

Let us know if that works.

**Comment by Fryie** [comment]
Unfortunately it doesn't. It just adds both entries below and leaves the "normal" status field empty.

My swagger_doc JSON file looks weird anyway. It only contains an array "apis" with the top-level resources, each having a "path" and a "description". Everything looks fine in the UI, though.

**Comment by dblock** [comment]
So does your JSON have that `responses` part?

You should hunt down how that value makes it into Swagger UI.

**Comment by Fryie** [comment]
I don't know. As said, my JSON is almost empty. I don't know where Swagger UI is getting all the information from, probably it's split into multiple files or something.

**Comment by dblock** [comment]
I would add this to a simple app first which has a working grape-swagger implementation, https://github.com/dblock/grape-on-rack, and we can look at the code if it doesn't work.

**Comment by Fryie** [comment]
Ok, I'll look into that.

**Comment by migmartri** [comment]
@Fryie, @dblock did you figure this out? I am running into exactly the same issue.

I just want to change the default status code to `202` (instead of `201`) and if I do it using the code below if does not get exposed. Then if I use http_codes it just adds extra status codes not changing the default one.

```
post :foo do
  status 202 
end
```

Thanks, 
Miguel

**Comment by dblock** [comment]
Haven't looked at it.

**Comment by LeFnord** [comment]
@migmartri please open a new issue, to set non common http status codes, this one is for the old spec  and it seems your one is for the new spec

**Comment by migmartri** [comment]
I have just created a new issue as you suggested https://github.com/ruby-grape/grape-swagger/issues/533

I did not notice the `swagger-1.2` tag.

Thank you!

**Comment by LeFnord** [comment]
solved in the actual version
