### ISSUE TITLE
how to set default param_type, instead of set param_type to every params over and over again?

### ISSUE THREAD

**Issue by TangMonk** [ruby-grape/grape-swagger#246]
the default param_type is `form`, actually the usually  is `body`

**Comment by dblock** [comment]
That's not generally true.

Are you setting it via `documentation` right now? It's implemented [here](https://github.com/tim-vandecasteele/grape-swagger/blob/768454bac676417ad1fce0d1da2bf82835fbc6c6/lib/grape-swagger.rb#L242). I would refactor that to be a method and then you could monkey patch it for your application.

**Comment by LeFnord** [comment]
solved in the actual version, using `body` only ones, all params (beside path params) would be interpreted as body params

**Comment by vinceve** [comment]
Sorry to open this again. But wouldn't it be better to define a default for the whole api? In most cases you'll be building an API with the same sort of parameters everywhere (except in exceptional cases).

I think it would make the code cleaner to maybe define it once in the "add_swagger_documentation" method and then to make it overridable in every parameter (like it is now)

**Comment by LeFnord** [comment]
Hi @vinceve, please make a new issue  
many things have changed, so I closed it …

But this is definitely the expected behavior of OPAI 2.0/3.0, but the handling of it crime the grape side is a bit different. 

Any suggestion in form of a PR is welcome,  
at least a spec for documentation purposes

**Comment by mauroc** [comment]
+1 for vinceve's suggestion. Has this ever been implemented? If not to the whole API, can it be applied at the 'desc' level?
