### ISSUE TITLE
nested namespace with desc not work

### ISSUE THREAD

**Issue by TangMonk** [ruby-grape/grape-swagger#248]
``` ruby
 namespace :order, desc: "order" do

      namespace :product, desc: "product" do
       ....
      end
end
```

but the swagger_doc:

``` json
{
"path": "/order.{format}",
"description": "Operations about orders" 
}
```

**Comment by dblock** [comment]
Can you write a test that reproduces this? I am pretty sure nested namespaces work fine.

**Comment by jaman1020** [comment]
I'm actually having the same problem, all of my base routes are there but the nested ones do not show up. I'm using grape 0.11 and grape swagger 0.10.1 set up pretty standard. Maybe an issue with the latest version of grape?

**Comment by jaman1020** [comment]
Sorry this was a confusion on my part on how swagger actually worked. I didn't realize that you had to go to swagger_doc/resource_name.json to get the nested routes, I assumed everything would be in the root json file.

Maybe @TangMonk's issue too?

**Comment by brodock** [comment]
same here :+1: 

I have two mounted APIs with one namespace in each. The first one works, the second don't.

**Comment by atomless** [comment]
+1
