### ISSUE TITLE
Models not following swagger spec 1.2 when Grape entity contains root

### ISSUE THREAD

**Issue by aitortomas** [ruby-grape/grape-swagger#250]
When using Grape entities, if `root`is defined, the spec returned may not follow the swagger spec 1.2 for the ID field.
As per https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#527-model-object the ID field "MUST be the name given to {Model Name}".
When using Grape entities if root is defined and different than model name, the spec generated does not follow the above rule.
As an example:

```
class AutosEntity < Grape::Entity
    root 'cars', 'car'
    ...
end
```

will generate:

```
...
"AutosEntity":{  
         "id":"car",
...
```

This is due to:
https://github.com/tim-vandecasteele/grape-swagger/blob/master/lib/grape-swagger.rb#L386

It causes that swagger-ui shows as schema:

```
Inline Model {
undefined
}
undefined {
}
```

**Comment by dblock** [comment]
Would appreciate a PR with a spec and maybe even a fix?

**Comment by LeFnord** [comment]
solved in the actual version
