### ISSUE TITLE
response Content Type

### ISSUE THREAD

**Issue by dan-corneanu** [ruby-grape/grape-swagger#255]
Hello, 
how can I influence the content of the `<produces type="array">` element in the generated swagger description?

I have the following API configuration

``` ruby
 version 'v1', vendor: 'Harmoney'
 content_type :json, 'application/json'
 content_type :csv,  'text/csv'
 default_format :json
```

the result I get is

``` xml
<produces type="array">
  <produce>application/xml</produce>
  <produce>application/json</produce>
  <produce>application/octet-stream</produce>
  <produce>text/plain</produce>
</produces>
```

I would have expected to only see application/json and text/csv. Am I wrong?

**Comment by dblock** [comment]
Without looking at the code this looks like a bug. Would you please write a test that reproduces this? Shouldn't be hard to fix.

**Comment by dan-corneanu** [comment]
I'll give it a look this week.

**Comment by dan-corneanu** [comment]
@dblock can you please have a look at this test and let me know if the expected behaviour is correct?
https://github.com/dan-corneanu/grape-swagger/commit/cc6856bfdd64ac9470dcf9d35ee2305023b20345

**Comment by dblock** [comment]
I think the test looks right.

**Comment by atomless** [comment]
I'm seeing the same issue with : grape (0.16.2), grape-entity (0.5.1) & grape-swagger (0.20.3).
This:
```Ruby
      add_swagger_documentation \
        version: 'v1',
        doc_version: '1',
        mount_path: '/api/documentation.json',
        format: :json,
        hide_documentation_path: true,
        produces: [ 'application/json' ],
        info: {
          title: 'Title Of API',
          description: 'A RESTful API bla...'
        }
```
outputs this in the json:
```JSON
...
"produces": [
"application/xml",
"application/json",
"application/octet-stream",
"text/plain"
],
...
```

**Comment by LeFnord** [comment]
solved in the actual version
