### ISSUE TITLE
Description in block

### ISSUE THREAD

**Issue by u2** [ruby-grape/grape-swagger#257]
```ruby
desc "Returns your public timeline." do
  detail 'more details'
  params  API::Entities::Status.documentation
  success API::Entities::Entity
  failure [[401, 'Unauthorized', "Entities::Error"]]
  named 'My named route'
  headers [XAuthToken: {
             description: 'Valdates your identity',
             required: true
           },
           XOptionalHeader: {
             description: 'Not really needed',
            required: false
           }
          ]
end
```
The description in block is not supported?

**Comment by dblock** [comment]
@u2 Care to elaborate? Thanks.

**Comment by dm1try** [comment]
Same here, if I use `params` or `success` in the `desc` block then my endpoints totally dissapear. (latest grape/swagger/entity, on grape 0.10.0 only `swagger_doc/entity` endpoint `not found`..)
I'll try to add a spec later, not sure who is to blame..

**Comment by birbird** [comment]
Same with me.
u2's just copied sample code from Grape doc which is from https://github.com/intridea/grape#describing-methods

I am using 'grape', '~> 0.12.0', if remove some lines from the desc block, I find
the failure [[401, 'Unauthorized', "Entities::Error"]] will break the doc of the endpoints, can not expand
the headers show in the doc, but the content can not be recognized
