### ISSUE TITLE
Protect grape swagger with an auth

### ISSUE THREAD

**Issue by florrain** [ruby-grape/grape-swagger#269]
Hello,

I'm not sure I read something about recommendations in the readme in terms of securing swagger inside a Rails+Grape app.

I'd either like to use a custom auth system, I'm currently using Authlogic with Rails right now but a simple basic auth or authorization header would do it. 
I just want swagger to be accessible to devs and not whoever finds the url to the json specs.

Thanks.

**Comment by dblock** [comment]
You should probably go the middleware route, however grape-swagger would probably also benefit from a `before`-type filter.

**Comment by whatasunnyday** [comment]
As a stop gap, you can use a middleware like this:

```ruby
require 'rack'

class ProtectSwagger
  def initialize(app)
    @app = app
  end

  def call(env)
    request = ActionDispatch::Request.new(env)
    if request.subdomain == 'api' && request.path =~ /\A\/swagger/
      auth = Rack::Auth::Basic.new(@app) do |username, password|
        'secret' == password
      end
      auth.call(env)
    else
      @app.call(env)
    end
  end
end
```

Note: You may need to change `if request.subdomain == 'api' && request.path =~ /\A\/swagger/` depending on how your grape app is structured.

**Comment by LeFnord** [comment]
this isn't grape-swagger related, it should be done by your API
