### ISSUE TITLE
Markdown not parsed when `config.eager_load` is set true

### ISSUE THREAD

**Issue by calfzhou** [ruby-grape/grape-swagger#270]
I'm using `GrapeSwagger::Markdown::RedcarpetAdapter` to parse markdown in API doc, it works well in development and test environment. But when the API goes production, all markdown cannot be parsed. I found that it is because in production's environment configuration, `config.eager_load` is set to `true`. Is there any way to make markdown work as well as not change `config.eager_load`?

Here is the screenshot of my API doc when  `config.eager_load` set to `false`:
<img width="224" alt="111" src="https://cloud.githubusercontent.com/assets/3761553/8492411/c7d4a198-217b-11e5-8f61-6e5b484415c7.png">

And once change `config.eager_load` to `true`, it became this:
<img width="270" alt="222" src="https://cloud.githubusercontent.com/assets/3761553/8492416/cfd5aac2-217b-11e5-9c76-eec5d7336794.png">

**Comment by dblock** [comment]
Looks like a bug, or at least a strange side effect of eager-loading. Next steps should be to dig in why this is actually happening at rendering time.

**Comment by calfzhou** [comment]
I figured out my special case. I have multiple APIs in one  server, and I called `add_swagger_documentation` on three classes. Two of them set markdown option, only one (maybe the last one in alphabet order) not set markdown. I'm not sure, but maybe when `eager_load` is set to true, since `@@markdown` is a class variable, the final `add_swagger_documentation` call overwrites previous configurations.

Now i can simply avoid this problem by set the the value of `markdown` option to the last `add_swagger_documentation` call.

I've no idea whether calling `add_swagger_documentation` multiple times is a good practice, but in my scenario I really need serve several different document endpoints.

Please feel free to close this issue if there is no need to change in the gem side. Thank you for this great tool!

**Comment by dblock** [comment]
That makes sense, `@@markdown` is not a safe way for doing this IMO, it's not threadsafe and clearly is causing problems with eager-loading - I think we should fix it, here's a similar story: https://github.com/LTe/grape-rabl/issues/37

**Comment by LeFnord** [comment]
Markdown parsing no longer needed (OAPI spec 2.0)
