### ISSUE TITLE
Generate markdown doc

### ISSUE THREAD

**Issue by u2** [ruby-grape/grape-swagger#278]
Is there a way for generating markdown doc from grape swagger?

**Comment by dblock** [comment]
We do this in https://github.com/artsy/doppler, see `modelref` in https://github.com/artsy/doppler/blob/93612c9c3fcb236240b2fc0419c456e68b83fb11/app/controllers/pages_controller.rb for example. It's a bit involved, I think a gem that automatically generates markdown reference for an API would be cool.

**Comment by rngtng** [comment]
There's https://github.com/vericred/grape-apiary which does similar too. But I havn't looked much into it...
