### ISSUE TITLE
The document example parameter make no sense

### ISSUE THREAD

**Issue by birbird** [ruby-grape/grape-swagger#279]
The code from grape-swagger document

```
params do
  requires :id, type: Integer, desc: 'Coffee ID'
  requires :temperature, type: Integer, desc: 'Temperature of the coffee in celcius', documentation: { example: 72 }
end
```

Does the example field make sense? It will not show on swagger-ui.
Becuase the swagger spec does not have any example definition on parameter object
see http://swagger.io/specification/#parameterObject

**Comment by dblock** [comment]
It's possible that this is just a copy-paste. If you're sure, make a PR that removes it.

**Comment by birbird** [comment]
I created #280 for this issue.

**Comment by calfzhou** [comment]
my documentation.example actually works and i'm now depends on this feature....

**Comment by mfkp** [comment]
I looked this up, I had it in my code and I think I remember it working, but now on the latest version, the example parameter doesn't do anything.

**Comment by LeFnord** [comment]
solved in the actual version
