### ISSUE TITLE
0.10.2 unreleased

### ISSUE THREAD

**Issue by SkyWriter** [ruby-grape/grape-swagger#281]
The 0.10.2 release fixes quite an important bug related to working with the latest Grape, but it's not yet on Rubygems.

Would you please push the gem when you got time?

**Comment by dblock** [comment]
There's some discussion in https://github.com/tim-vandecasteele/grape-swagger/pull/280 that I'd like to clear before cutting this release. Maybe you want to pitch in?

**Comment by dblock** [comment]
I've released 0.10.2.

**Comment by rngtng** [comment]
yay, thanks!
