### ISSUE TITLE
cannot disable suffix (.json) with grape 0.13.0

### ISSUE THREAD

**Issue by TangMonk** [ruby-grape/grape-swagger#290]
![image](https://cloud.githubusercontent.com/assets/3498786/9514902/4ad995ce-4cd0-11e5-9de3-a6966967d6b5.png)

it will make request as `Started POST "/api/v1/user/login(.json)" `

I am try to set `hide_format: true`, but not work

this problem only appears at grape `0.13.0` 

grape `0.11.0` works fine.

**Comment by dblock** [comment]
@TangMonk Which part is not working? Maybe show us what you get with 0.11 vs. 0.13?

**Comment by TangMonk** [comment]
thanks for your reply.

notice that rails log `Started POST "/api/v1/user/login(.json)"`, It request `/api/v1/user/login(.json)`, not `/api/v1/user/login.json` or `/api/v1/user/login`, it contain the unnecessary brackets

**Comment by dblock** [comment]
I don't think the problem is here, it's in swagger-ui ,are you using grape-swagger-rails? Can we see that project or this one?

**Comment by epaulet** [comment]
This was fixed with commit 24692e76197282b787fce4b4a5e9507283269939, but wasn't not released yet.

The current release does not work with Grape 0.12.0.

**Comment by dblock** [comment]
@epaulet Right, grape-swagger 0.10.2 should not have this issue, @TangMonk can you confirm?

**Comment by TangMonk** [comment]
@dblock @epaulet thanks!

Yes! That's 0.10.1 problem, 0.10.2 works fine!
