### ISSUE TITLE
Undefined method `pluralize' for "doc":String in doc_methods.rb

### ISSUE THREAD

**Issue by atomless** [ruby-grape/grape-swagger#293]
When visiting the swagger docs path for my project I just get this error: `NoMethodError at /api/documentation
undefined method `pluralize' for "doc":String
Ruby /Library/Ruby/Gems/2.0.0/gems/grape-swagger-0.10.2/lib/grape-swagger/doc_methods.rb: inblock(2levels)insetup, line 382`

**Comment by dblock** [comment]
This comes from ActiveSupport, looks like we may be missing a `require` of something specific somewhere.

**Comment by atomless** [comment]
Still having this issue with grape-swagger latest code. Here's the stack trace:
![nomethoderror at _api_documentation-1](https://cloud.githubusercontent.com/assets/28726/9699215/4fc3c0e2-53d2-11e5-9081-779102f3911a.png)

**Comment by atomless** [comment]
Is there a quick work around I can use for this?

**Comment by dblock** [comment]
See if `require 'active_support/core_ext/string'` fixes it?

**Comment by atomless** [comment]
Yep that fixes it. Thanks @dblock !

**Comment by dblock** [comment]
So active_support is not technically required by grape-swagger I believe, so we need to either explicitly require it, or we need to rewrite `pluralize` in that code. I'd like someone to contribute a fix here.

**Comment by LeFnord** [comment]
solved in the actual version
