### ISSUE TITLE
Generate consumes in swagger spec

### ISSUE THREAD

**Issue by fab-girard** [ruby-grape/grape-swagger#298]
Hello,
I don't see any way to generate [consumes](https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#operationConsumes) in swagger spec with grape-swagger gem.
Is there any way to generate it or maybe a chance to improve grape-swagger ?

I think this info could be usefull for instance in swagger-ui in order not to use curl -d URLENCODED_JSON_PARAM when param_type is form and data_type is json. Because, in this case and up to now, swagger-ui is encoding my non-primitive json params :( 

Regards,
Fabien

**Comment by dblock** [comment]
I think this is a new feature request.

**Comment by fab-girard** [comment]
Ok. I agree with you. An idea maybe for the input we could use in api definition to generate that consumes ? If you share it, I could spend time on this new feature if I have enough.

**Comment by calfzhou** [comment]
+1

my swagger-ui.min.js always warning me that `server doesn't consume application/x-www-form-urlencoded, try ["application/json"]`

**Comment by dan-corneanu** [comment]
+1

**Comment by LeFnord** [comment]
solved in the actual version
