### ISSUE TITLE
self.entity_name undocumented.

### ISSUE THREAD

**Issue by Micka33** [ruby-grape/grape-swagger#299]
This  feature is undocumented in grape-entity.
I spent hours looking for it.

![screen shot 2015-09-23 at 18 57 26](https://cloud.githubusercontent.com/assets/3918958/10052056/1a6cce46-6225-11e5-82d7-e789a6b33fc0.png)

**Comment by dblock** [comment]
Would appreciate a PR for the docs please!

**Comment by LeFnord** [comment]
solved in the actual version
