### ISSUE TITLE
resource vs namespace?

### ISSUE THREAD

**Issue by waynn** [ruby-grape/grape-swagger#303]
I've been trying for the last four days to set up a rails 4 project with `grape`, `grape-entity`, and `grape-swagger`, and I've been having difficulty getting the API documentation up and running. What happens is I get the top level element, but it doesn't show any specific API calls, and I can't do any testing. I've copied a basic version below, but I have two questions:
1. Does it work if I'm using `resource` instead of `namespace`, as the example shows?
2. Do I need to put `:packages` into its own module, mounting `PackageApi` inside the `Base` class? And should `PackageApi` inherit from `Base` or from `Grape::API`?

Thanks for any help! I've been trying to figure this out for awhile now.

```
require 'grape-swagger'

module API
  class Base < Grape::API
    version 'v1', using: :path
    format :json

    resource :packages do
      desc 'Return enabled packages'
      get do
        present Package.enabled
      end
    end
  end
end
```

**Comment by dblock** [comment]
Where's your grape-swagger declaration? It should all work, regardless of `resource` or not, these are just aliases, but I could be wrong.

**Comment by mauroc** [comment]
did you ever get this to work? I am having the same problem.

**Comment by LeFnord** [comment]
solved in the actual version
