### ISSUE TITLE
Question about body parameters of type Array

### ISSUE THREAD

**Issue by rkrage** [ruby-grape/grape-swagger#306]
So here I have the definition of my endpoint, the format of the payload being sent, and the documentation generated by grape-swagger:  https://gist.github.com/rkrage/b0ddd66b395cd9aa741d

Sending the described payload populates the parameters just fine in grape, but the documentation doesn't look quite right in the swagger UI.

![swagger UI](http://i.imgur.com/qPEaKEm.png)

(Also for some reason the name of the param is "body" instead of "data")

After digging a bit, I _think_ this is just a limitation of swagger and it even looks like grape-swagger sort of hacks multiple body params into form params to make the UI look pretty, but I guess it can't do that for params with type Array.

Is my only option to define one top level body param with the fields nested below?

```ruby
params do
  optional :root, type: Hash, desc: 'Nested options'
end
```
```json
{
   "root":{
      "details":"this is my payload",
      "data":[
         {
            "key1":"value1"
         },
         {
            "key2":"value2"
         }
      ]
   }
}
```

**Comment by dblock** [comment]
Maybe this is a question you want to link/port with Swagger-UI?

**Comment by rkrage** [comment]
The data parameter having an incorrect name is probably something I should bring up on the swagger-ui project, but I'm just wondering if the JSON generated by grape-swagger is expected given my endpoint definition.

```json
{
   "notes":"",
   "summary":"Create a request",
   "nickname":"POST-requests---format-",
   "method":"POST",
   "parameters":[
      {
         "paramType":"form",
         "name":"details",
         "description":"Some string",
         "type":"string",
         "required":false,
         "allowMultiple":false
      },
      {
         "paramType":"body",
         "name":"data",
         "description":"Some JSON array",
         "type":"Array",
         "required":false,
         "allowMultiple":false
      }
   ],
   "type":"void"
}
```

**Comment by dblock** [comment]
It looks OK to me from a cursory look.

**Comment by rkrage** [comment]
Fixing the UI issue was as simple as forcing the param_type to be a form. I'm not a huge fan of this solution, but I don't think there's a better way until #101 / #49 gets resolved. Closing this for now.
