### ISSUE TITLE
swagger spec 2.0

### ISSUE THREAD

**Issue by LeFnord** [ruby-grape/grape-swagger#307]
please could you create a branch for it …

I had done some work to upgrade grape-swagger to produce swagger spec 2.0
(this is a requirement for AWS for example).

Many work is done, and now I want to make a PR against this branch, to discuss it and make it more complete.

BTW, it is in my opinion it is impossible to make it complete, cause swagger2.0 doesn't support nested params with different types, this is also a point, which I want to discuss.

the actually work can be found here: https://github.com/LeFnord/grape-swagger

**Comment by dblock** [comment]
Thanks! Just make a PR into master, I'll merge it into a branch if it gets us a step further and add comments.

**Comment by LeFnord** [comment]
are you sure, this introduces breaking changes …

**Comment by dblock** [comment]
I am not going to merge it into master.
