### ISSUE TITLE
How do I specify a model schema type with grape-swagger?

### ISSUE THREAD

**Issue by pswenson** [ruby-grape/grape-swagger#313]
If you look at this screenshot:

![screenshot](https://s3.amazonaws.com/f.cl.ly/items/18123k0s443n2J2K1B3Y/Screen%20Shot%202015-10-30%20at%203.14.47%20PM.png)

you will see that for the petstore example here: http://petstore.swagger.io there is a model/model schema that describes the json structure for the body in a post.

the swagger json is here:  http://petstore.swagger.io/v2/swagger.json

How can grape-swagger be used to hook in a model/model schema as shown in the screenshot?
I don't see any documentation on this swagger feature.  Thanks for any thoughts!

**Comment by LeFnord** [comment]
your example is for swagger-2.0, is it what you want?

at the moment, this isn't implemented yet in the swagger-2.0 branch
but I'm on right now :wink:, cause this is the last before the release and to ship a valid MVP

**Comment by LeFnord** [comment]
solved in the actual version

**Comment by bmedici** [comment]
Hello, glad to read it has been integrated in the newer versions, but I can't find the documentation for this? Could you point me to the relevant page ?
