### ISSUE TITLE
Support grape-entity 0.5.x in 0.11.x series

### ISSUE THREAD

**Issue by dmitry** [ruby-grape/grape-swagger#314]
grape-entity made a lot of changes within it's interface: https://github.com/ruby-grape/grape-entity/blob/master/CHANGELOG.md#050-next

Can we discuss here, how we can start to work on supporting the grape-entity before it's release?
- First of all, this field https://github.com/ruby-grape/grape-swagger/blob/master/grape-swagger.gemspec#L15 should be updated and point to the github version. 
- Minor version should be incremented to 0.11.
- Check the failing specs and try to fix them.

What else is lost here?

**Comment by dblock** [comment]
I locked down .gemspec in #315.

**Comment by LeFnord** [comment]
solved in the actual version
