### ISSUE TITLE
How to hide version from path in swagger

### ISSUE THREAD

**Issue by synth** [ruby-grape/grape-swagger#317]
We are using path versioning in grape. The api is accessible via /api/v2 where v2 is the version.

We would like the swagger documentation to have a base path of /api/v2 and all endpoints to omit this.

From looking at the source, this does not currently seem possible. Is there a best practice here?

From looking at GrapeSwagger::DocMethods#parse_path, it seems it would be an easy place to put a configuration option to exclude the path from the output.

I'm happy to put together a PR if this sounds interesting.

Thoughts?

**Comment by synth** [comment]
I've discovered that this is only an issue when the grape api is structured so that the version is a module such as

````
module Api
  module V2
    class Base < Grape::Api
     mount Api::V2::Thing
     add_swagger_documentation
    end
  end
end
````

**Comment by synth** [comment]
PR: https://github.com/ruby-grape/grape-swagger/pull/319

**Comment by LeFnord** [comment]
for the actual, see: [add_version](https://github.com/ruby-grape/grape-swagger#add_version)
