### ISSUE TITLE
'info' setting is not functioning as expected.

### ISSUE THREAD

**Issue by NeMO84** [ruby-grape/grape-swagger#320]
It seems from the description that the 'info' parameter to the add_swagger_documentation should be applied at the top level of the API. Not per call. 

The setting doesn't work because when going to the mount point after initializing the API, the extra_info (https://github.com/ruby-grape/grape-swagger/blob/4b72319bbe9679df4e2890156455ae12b5f649ad/lib/grape-swagger/doc_methods.rb#L403)  is reset per get call. 

```
add_swagger_documentation(info: {
      title: "My API",
      description: "My API description",
      contact: "api@myapi.com"
})
```

For it to function properly, I had to change the extra_info variable to be a class level variable, similar to the other class variables in that scope. 

Am I missing something or is this a bug?

**Comment by dblock** [comment]
It's probably just a bug, feel free to PR a fix.

**Comment by LeFnord** [comment]
solved in actual versions
