### ISSUE TITLE
How to customize endpoint Title/Description?

### ISSUE THREAD

**Issue by herberzt** [ruby-grape/grape-swagger#324]
Looking to customize my endpoint title/description. Honestly I don't know what it is actually called. If you look at the http://petstore.swagger.io/ you will see that the pet endpoint has the title "Everything about your pets". The default is "Operations about [endpoint]". Where exactly can this be changed. In case this might make things a little easier all of the endpoints we have are are in one api.rb file. They are not separated into their own files. Thanks in advance for the help.

EDIT: In swagger terms this is apparently considered the "tag description" in Swagger 2.0 and "api declaration description" in 1.2

**Comment by dblock** [comment]
There're two ways to do this. Add a `desc` at a namespace level where the namespace is the same name as the endpoints group (looking at https://github.com/ruby-grape/grape-swagger/blob/03ee40d41d71063236c4b0b1d468f69978ab308e/lib/grape-swagger/doc_methods.rb#L442) and through localization, which is documented here: https://github.com/ruby-grape/grape-swagger#namespacesresources-description.

**Comment by herberzt** [comment]
Thanks
