### ISSUE TITLE
is_array no longer supported in Grape

### ISSUE THREAD

**Issue by Inkybro** [ruby-grape/grape-swagger#334]
Grape has deprecated passing options to `desc` as a hash:

``` ruby
desc "Blah blah blah",
  entity: SomeEntity,
  is_array: true
```

Today they are expecting this to become:

``` ruby
  desc "Blah blah blah" do
    entity SomeEntity
    # is_array is unusable here
  end
```

In its implementation there is no place for is_array (makes sense). The question is, how might one be able to still utilize is_array without passing it in through the options hash (and therefore, producing the deprecation warnings)? 

Is it simply not possible at this time? Is this something planning to be addressed? Or more simply still, am I just missing something, here?

Thanks.

**Comment by dblock** [comment]
@Inkybro You closed this, care to elaborate for the next person?

**Comment by Inkybro** [comment]
@dblock I was meaning to close it while I looked a little deeper into the problem myself. I meant to re-open it if my efforts turned out to be fruitless (which they did). Anyhow, I'm reopening this issue now. 

Thank you for replying. I would likely not have noticed this for a long time, and have been looking forward to hearing something on this, so I'm glad you wrote me back here.

I'm not sure exactly what you'd like me to elaborate on but I'd be happy to do so if you can clarify a little bit for me. Let me know if there is anything further I can provide or do to help.

Thanks again!

**Comment by dblock** [comment]
@jaronson, you seem to have a commit fixing this? PR something into Grape?

**Comment by nathandcornell** [comment]
Sorry for bringing this up again, but my team is running into this issue as well.

Example code:
```
        desc "Get Access" do
          detail  "Returns accesses"
          is_array true
          success code: RESPONSE_CODE[:ok], message: "Access Entities", model: V1::Access::Entity
       ...
```

Resulting error:
`undefined method `is_array' for #<#<Class:0x000055b10049cdf0>:0x000055b10049c2d8> Did you mean? is_a?`

And as noted above, adding it as a named parameter to `desc` results in a deprecation warning.

Has there been any movement on this?

**Comment by LeFnord** [comment]
mmh I'm actual using it in the block style without problems,  
tested with grape 1.2.5 and > 1.3.0, mauybe you have to update grape

**Comment by nathandcornell** [comment]
Yep, upgrading solved it!
