### ISSUE TITLE
Namespace Description Not Showing Up

### ISSUE THREAD

**Issue by deanpapastrat** [ruby-grape/grape-swagger#350]
I'm having an issue where adding a `desc: "description"` to the namespace does not cause the description for the namespace to show up in swagger ui.

An example:
```ruby
namespace 'people', desc: "Access people from the DB" do
  get "profile" do
    # profile code here
  end

  get ":id" do
    # show code here
  end
end
```

Gives this result:
<img width="967" alt="screen shot 2016-03-10 at 5 01 25 pm" src="https://cloud.githubusercontent.com/assets/4662240/13686070/dbdcbfd2-e6e1-11e5-8adf-68eb07150380.png">

Whereas I thought it should be (edited in-browser):
<img width="965" alt="screen shot 2016-03-10 at 5 03 15 pm" src="https://cloud.githubusercontent.com/assets/4662240/13686091/043bc4be-e6e2-11e5-854b-ae93eede5cb7.png">

I'm on Grape-Swagger 0.10.4, Grape-Swagger-Rails 0.2.0, and Grape 0.14.0.

Am I doing something wrong?

Thanks!

**Comment by dblock** [comment]
Just a hunch, try putting `desc` above the namespace:

```ruby
desc 'bla bla bla'
namespace :bla do ...
```

Did it change anything?

**Comment by LeFnord** [comment]
this PR #348  could maybe solve your problem, if you want to try the swagger-2.0 branch

**Comment by deanpapastrat** [comment]
I tried @dblock's solution but that didn't seem to work for me on the current version of grape-swagger or the swagger-2.0 branch.

Upgrading to the swagger-2.0 branch and using the code I posted above made it work for me.

Thanks for the help!

**Comment by dblock** [comment]
:+1:
