### ISSUE TITLE
NoMethodError undefined method `exposures' for API::Entities::Post:Class

### ISSUE THREAD

**Issue by kkan** [ruby-grape/grape-swagger#355]
I'm trying to set entity in desc method, but it throws the error.

```
module API
  module Entities
    class Post < Grape::Entity
      expose :id, documentation: {type: 'Integer',  desc: "Id"}
      expose :title, documentation: {type: 'String',  desc: "Title"}
    end
  end
end

module API
  module V1
    class Posts < Grape::API
      version 'v1'
      format :json
      content_type :json, "application/json;charset=UTF-8"
      rescue_from :all

      resource :posts, desc: 'Posts' do
        desc "List of all posts", entity: API::Entities::Post
        get do
          present Post.all, with: API::Entities::Post
        end
      end
    end
  end
end
```

versions of gems:
gem 'grape', '~> 0.14.0'
gem 'grape-entity', '~> 0.5.0'
gem 'grape-swagger-rails', '~> 0.2.0'

In these versions all is fine:
gem 'grape', '~> 0.13.0'
gem 'grape-entity', '~> 0.4.8'
gem 'grape-swagger-rails', '~> 0.1.0'

**Comment by LeFnord** [comment]
background: grape-entity, changed the handling of exposures, up to version 0.4.8, exposures was a simple array of the keys, with 0.5.0 this are exposure objects …

maybe you can give the swagger-2.0 a try, this can handle both versions

**Comment by Kiwwa** [comment]
@fredwu and I solved this issue with these versions;

``` 
grape 0.15.0
grape-entity 0.4.8
grape-swagger 0.10.2
```

grape-entity has no dependency for grape, so you can just pick an older version and it will probably work :smile:
