### ISSUE TITLE
URL for GET request does not include version

### ISSUE THREAD

**Issue by praveenangyan** [ruby-grape/grape-swagger#359]
I have used the following code to generate the swagger documentation:
`add_swagger_documentation(api_version: "v1", add_version: true, mount_path: "/api/v1/swagger_doc", hide_documentation_path: true, hide_format: true)`

However the GET request URL in the documentation is just /api/<model_name>. The v1 is missing in the GET request URL.

How do I fix this?

**Comment by LeFnord** [comment]
I'll have a look on it

**Comment by LeFnord** [comment]
did it, and the spec [api_swagger_v2_global_configuration](https://github.com/LeFnord/grape-swagger/blob/master/spec/swagger_v2/api_swagger_v2_global_configuration_spec.rb) says, it is ok

**Comment by praveenangyan** [comment]
Unfortunately, if you look at the documentation created here: https://trial-promoter-app-praveenangyan.c9users.io/api_documentation#!/clinical_trials/getApiClinicalTrials,

it still looks like the get and the post requests are not using /api/v1 in the generated documentation schema.

**Comment by praveenangyan** [comment]
I've fixed this using routes that route from /api/resource_name to /api/v1/resource_name, so I am good for now.

**Comment by poori** [comment]
Not sure if I'm doing something wrong too, but for future users, I solved this by downgrading to 0.10.5

**Comment by LeFnord** [comment]
fixed here: https://github.com/ruby-grape/grape-swagger/pull/405
