### ISSUE TITLE
Grape: route_xxx methods have been deprecated

### ISSUE THREAD

**Issue by ngonzalez** [ruby-grape/grape-swagger#364]
Grape Route model route_* methods have been deprecated
https://github.com/ruby-grape/grape/blob/master/lib/grape/router/route.rb#L100

Grape-Swagger still uses a lot of these methods, and the deprecation warnings can be annoying ..

**Comment by LeFnord** [comment]
yeap, this breaking change is known,
as I mentioned in the [grape group](https://groups.google.com/forum/#!topic/ruby-grape/kdP1hTSILLw)
the adoption of is planned for 0.21.0 release

**Comment by ngonzalez** [comment]
@LeFnord Thanks

**Comment by dblock** [comment]
Do we want a 0.10.6 or 0.11.0 that locks a higher version of Grape and fixes the deprecations?

**Comment by LeFnord** [comment]
@dblock … think we should use 0.11.0 for grape >= 0.15.0 to indicate breaking change

**Comment by dblock** [comment]
Reopening this for a 0.11.0. It's a little more involved than I thought.

**Comment by SuperMasterBlasterLaser** [comment]
Is there any Pull requests that fixes this?

**Comment by pamit** [comment]
This may fix this problem,

gem 'grape', '>= 0.16.2'
gem 'grape-entity', '< 0.5.0'
gem 'grape-swagger', '0.11.0'
gem 'grape-swagger-rails'#,  '~> 0.0.8'

It works for me.

**Comment by dblock** [comment]
I'll close this, we have released compatible versions at this point. Understand that the matrix is a little complicated, but it gets better as we move forward. See https://github.com/ruby-grape/grape-swagger#version.
