### ISSUE TITLE
Conditional Exposure and model schema

### ISSUE THREAD

**Issue by renelux** [ruby-grape/grape-swagger#373]
Could someone implement Conditional Exposure for the model schema? [https://github.com/ruby-grape/grape-entity#conditional-exposure](Conditional Exposure)

**Comment by LeFnord** [comment]
feel free to dive in :wink:

**Comment by renelux** [comment]
If someone could point me in the right direction then I don't mind at all. I am new to grape and swagger, I would have to take a very deep dive first to understand how it all ties together.

**Comment by LeFnord** [comment]
please could explain a bit more the use case, or what you want to achieve?
