### ISSUE TITLE
How add model definitions of the grape identities ?

### ISSUE THREAD

**Issue by matteofuzz** [ruby-grape/grape-swagger#379]
I can't understand how add swagger v.2.0 model definitions of the grape entities, the README is obviously outdated (it seems refer to old swagger 1.2 version) https://github.com/ruby-grape/grape-swagger#models.

**Comment by LeFnord** [comment]
yeap, you are right, the README seems mostly to be the one of swagger-1.2 branch, but that was intended, to not to much introduce breaking changes :wink: 

for adding response definitions, please refer to: [#using-an-options-hash](https://github.com/ruby-grape/grape-swagger#using-an-options-hash, there the response definitions would be defined via `success: …`, and/or `failures …`, as well the example is a good starting point
