### ISSUE TITLE
Pickup API version from Grape

### ISSUE THREAD

**Issue by spier** [ruby-grape/grape-swagger#38]
I am unclear about how to specify the API version.
When I set `version 'v1'` then I still see `"apiVersion":"0.1"` in the JSON, which was a surprise for me.

More details:

In this implementation grape-swagger sets the **apiVersion** to **0.1**:

``` ruby
class Root < Grape::API
  version 'v1', :using => :path
  add_swagger_documentation
  [...]
end
```

``` json
{"apiVersion":"0.1","swaggerVersion":"1.1",...}
```

In this implementation grape-swagger sets the **apiVersion** to **v1**

``` ruby
class Root < Grape::API
  version 'v1', :using => :path
  add_swagger_documentation :api_version => "v1"
  [...]
end
```

``` json
{"apiVersion":"v1","swaggerVersion":"1.1",...}
```

The 2nd implementation example looks redundant to me. I might just not understand how this is meant to be used.

Is this the intended behavior?

**Comment by LeFnord** [comment]
it is implmented in actual version

**Comment by spier** [comment]
Awesome, thanks for letting me know!
