### ISSUE TITLE
The schemes tag is hard coded to https/http

### ISSUE THREAD

**Issue by wleeper** [ruby-grape/grape-swagger#380]
By hard coding the schemes tag sites that use http are broken by default.  You can use the try button because it 'tries' to use https. 

This needs to detect the scheme being used to render and use that.

Something like this:

```
      if schemes.is_a?(Proc)
        schemes.call(request)
      elsif schemes.is_a?(String)
        [schemes]
      elsif schemes.is_a?(Array)
        schemes
      else
        nil
      end
```

**Comment by wleeper** [comment]
Looking at http://swagger.io/specification/ it appears the default should be to not include it.

**Comment by LeFnord** [comment]
yeap, please replace this line [endpoint.rb#L30](https://github.com/ruby-grape/grape-swagger/blob/master/lib/grape-swagger/endpoint.rb#L30)
through your method and make a PR

**Comment by LeFnord** [comment]
solved with https://github.com/ruby-grape/grape-swagger/pull/382
