### ISSUE TITLE
When not specifying a model for http_codes invalid model is created

### ISSUE THREAD

**Issue by wleeper** [ruby-grape/grape-swagger#385]
**Expected:** The default behavior when no model is specified for an output 200/201 message should not produce a schema tag for the output.  This was how grape-swagger worked for in 0.10.2

**Actual:**  A definition matching the endpoint name and based on input parameters is created and used as the output schema.  This seems overly idealistic.  There are many cases where an endpoint will take in parameters and return something entirely different as output.  This puts a requirement to define an output model for every endpoint.

*The code that generates this definition  is something I would like to see used however to optionally create an input scheme based on the parameters, that is another story though*

Example:

```
...
        #
        desc 'Return reticulated value for a spline',
          http_codes: [
            { code: 200, message: 'is Spline Reticulated' },
            { code: 404, message: 'Not Found' }
          ]
        params do
          requires :id, type: Integer, desc: 'Spline id.'
        end
        get ':id/reticulated' do
          error!({ code: 404, message: 'Not Found' }) unless @@splines[params[:id] -1]
          present @@splines[params[:id] -1].reticulated
        end
...
```

Produces:

``` JSON
"/splines/{id}/reticulated": {
"get": {
"description": "Return reticulated value for a spline",
"produces": [
"application/json"
],
"parameters": [
{
"in": "path",
"name": "id",
"description": "Spline id.",
"type": "integer",
"format": "int32",
"required": true
}
],
"responses": {
"200": {
"description": "is Spline Reticulated",
"schema": {
"$ref": "#/definitions/Reticulated"
}
},
"404": {
"description": "Not Found"
}
},
"tags": [
"splines"
],
"operationId": "getSplinesIdReticulated"
}
},
```

**Comment by LeFnord** [comment]
in short, you suggest, only add a definition, if an entity was provided via `success` and/or `failures` as response, right?

**actual**: the definition would be generated from parameters if no entity was provided, yeap this is idealistic, but I'm fine with your suggestion, it would make things easier 😉 

btw: please don't refer to 0.1x.x series of the gem, they are totally different, you should always refer to the swagger-2.0 spec

**Comment by wleeper** [comment]
" if an entity was provided via success and/or failures as response" yes, that is my proposal.

The code that builds the model from params would be very useful though for an enhancement where you could pass in an optional parameter says something like params_as_schema, where it converts the params into a schema block (could even be inline) and renders that as a body parameter of type schema.  I will submit that enhancement once I explore exactly how it should work.

**Comment by LeFnord** [comment]
ok, this could be done …
and what did you think about the second thing,
creating a definition from body params for POST/PUT request?
this should be there in my opinion …

**Comment by LeFnord** [comment]
@wleeper give https://github.com/LeFnord/grape-swagger/pull/22 a try

**Comment by LeFnord** [comment]
is corrected here: https://github.com/ruby-grape/grape-swagger/pull/406
