### ISSUE TITLE
Could not find compatible gem for versions "grape"

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [ruby-grape/grape-swagger#386]
Hello.

I have added new version of grape-swagger to my project

`gem 'grape-swagger', github: 'ruby-grape/grape-swagger'`

When I try to bundle install it it gives me this error:

      Bundler could not find compatible versions for gem "grape":
       In snapshot (Gemfile.lock):
          grape (= 0.16.2)

       In Gemfile:
          grape x64-mingw32

       grape java

       grape-swagger x64-mingw32 was resolved to 0.20.0, which depends on
           grape (<= 0.14.0, >= 0.12.0) x64-mingw32

I think this is because of this Pull request #383. It forces this gem only accept 12 - 14 versions of Grape. However, last stable version of Grape is 16

Is it necessary to fix it on 14 version  of Grape?

**Comment by dblock** [comment]
Right now HEAD of grape-swagger, which is swagger-2.0 compatible, doesn't work with Grape 0.16.2. This is something that is forthcoming, @LeFnord can speak to that. You can use the released version of grape-swagger 0.11.0 with Grape 0.16.2.

**Comment by SuperMasterBlasterLaser** [comment]
@dblock This means that I just need to wait a bit?

**Comment by dblock** [comment]
Or you could contribute and try to make HEAD work against Grape 0.16.2!

**Comment by LeFnord** [comment]
yeap, that's right, the actual master supports grape upto 0.14.0, see [travis file](https://github.com/ruby-grape/grape-swagger/blob/master/.travis.yml)

support for grape > 0.16.2 is planned for the 0.21.0 release, but for the moment there is some work for the actual master

but as @dblock mentioned, contribute to make it work together with grape 0.16.2

see also: https://github.com/ruby-grape/grape-swagger/issues/364

**Comment by LeFnord** [comment]
release 0.20.1 should fix it

**Comment by SuperMasterBlasterLaser** [comment]
I have updated grape-swagger to 0.20.1 version and looked at Gemfile.lock. It showed me this:

     grape (0.14.0)
      activesupport
      builder
      hashie (>= 2.1.0)
      multi_json (>= 1.3.2)
      multi_xml (>= 0.5.2)
      rack (>= 1.3.0)
      rack-accept
      rack-mount
      virtus (>= 1.0.0)
    grape-entity (0.5.1)
      activesupport
      multi_json (>= 1.3.2)
    grape-swagger-rails (0.1.0)
      grape-swagger (>= 0.7.2)
      railties (>= 3.2.12)
    
I think last update just forced my app use only 0.14.0 version.

**Comment by LeFnord** [comment]
yeap, that is correct, but you can set it via `GRAPR_VERSION` env variable, see the Gemfile

**Comment by dblock** [comment]
@LeFnord, not for consuming gems, lock versions explicitly like this:

```ruby
grape, '~> 0.15.0'
grapes-wagger, '0.20.1'
```

**Comment by pioneerskies** [comment]
Sorry for my almost confused understanding, but I think that in the commit tagged with 0.20.1 the gemspec is locking the grape version <= 0.14... https://github.com/ruby-grape/grape-swagger/blob/v0.20.1/grape-swagger.gemspec

What am I missing here?

**Comment by LeFnord** [comment]
sorry for trouble … please refer to [#compatibility](https://github.com/ruby-grape/grape-swagger#compatibility)

**Comment by pioneerskies** [comment]
Ok. Thanks for your kind reply.

**Comment by dblock** [comment]
Should we close this or is there still something here that needs to get sorted out?

**Comment by LeFnord** [comment]
can be closed
