### ISSUE TITLE
How-to force Data Type

### ISSUE THREAD

**Issue by net1957** [ruby-grape/grape-swagger#387]
version: 0.20.0 
For a legacy application I'm using  parameters as:
````
            optional :start_date, type: Time, coerce_with: ApiTime,
                     desc: 'Select only Studies created or modified after this date. Format is dd/mm/yyyy hh:mm:ss. Invalid date is ignored',
                     documentation: { example: '24/12/2013 20:00:00' }

````
ApiTime  return a Time.
I'm awaiting a string as input

the generated json has "date-time" as  format

How can I force it to use "string" or omit the format key ? In the present state the example and the "data-type" column can perturb the user.

or perhaps I'm wrong in my usage ?

Regards

**Comment by LeFnord** [comment]
you have to differ between `type` and `format`, given on parameters the type as `Time` or `DateTime`, it would be documented as `type: "string", format: "date-time"`, to omit the format, use as parameter type `string` instead

**Comment by net1957** [comment]
I understand. But the code to generate the response is awaiting a Time parameter. Coerce is here to enforce that.
What would you suggest?

**Comment by LeFnord** [comment]
I suggest to set the parameter type correct to `DateTime`, cause in the description of the parameter  and in the example you are using it this way … 
if you are need it as time, one can simple convert it …
` foo = DateTime.new(2016, 4, 16).to_time`
