### ISSUE TITLE
Header is not displaying in Swagger UI

### ISSUE THREAD

**Issue by brahamshakti** [ruby-grape/grape-swagger#391]
This Code is not displaying header field in swagger UI

    desc "Return super-secret information", {
      headers: {
        "XAuthToken" => {
          description: "Valdates your identity",
          required: true
        },
       "XOptionalHeader" => {
         description: "Not really needed",
         required: false
       }
     }
    }

Earlier It used to be like 
![xauthtoken](https://cloud.githubusercontent.com/assets/2370848/14633863/2ae91a4c-063d-11e6-8ec5-d92aa39750ef.png)

But now it is showing no header field with above Code

![noxauthtoken](https://cloud.githubusercontent.com/assets/2370848/14633880/3f2073ac-063d-11e6-871d-39dcc3306845.png)

How do I fix this issue.

**Comment by LeFnord** [comment]
would be cool to write a spec (similar to this one: [api_swagger_v2_headers_spec.rb](https://github.com/ruby-grape/grape-swagger/blob/master/spec/swagger_v2/api_swagger_v2_headers_spec.rb)

so it could be reproduced

**Comment by brahamshakti** [comment]
I am using version 0.20.1.

**Comment by LeFnord** [comment]
ok, I see …
the so defined header should go into the response object,
to define header parameters, take a parameter and set the param_type to header

**Comment by brahamshakti** [comment]
It would be better if you could provide an alternative solution in form of some patch. Sorry but I think modifying 100s of apis to add just one extra parameter does not look a good approach. Can I accept some sort of patch in near future from you

**Comment by dblock** [comment]
@brahamshakti What exactly are you proposing? What would you like to write in your API? We'll accept patches from you, thanks.

**Comment by wleeper** [comment]
doing from the referenced test case

```
        params do
          optional :in_query, type: String, documentation: { param_type: 'query' }
          optional :in_header, type: String, documentation: { param_type: 'header' }
        end
```

does not really work.  It will make valid swagger spec, but the grape code is looking for the `in_header` parameter in the params list not in the header.  If it were a required field it would fail if you actually put the parameter in the header.

**Comment by LeFnord** [comment]
but the question is always, how to differ between stuff for request and stuff for response for documentation …

what are your thoughts?

**Comment by LeFnord** [comment]
@brahamshakti give it a try, and close the issue

**Comment by brahamshakti** [comment]
Thanks to @wleeper, my issue is resolved with this pull request. I am closing this issue for now. Thanks to all.
