### ISSUE TITLE
Uncaught TypeError: Cannot read property '$ref' of undefined

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [ruby-grape/grape-swagger#392]
This happens when I make params like this:

      params do
           requires :participants, type: Array do
              use :participant
            end
      end

When I define param as simple Array and write paramas inside of it.

This is most likely bug of [Swagger itself](https://github.com/ruby-grape/grape-swagger/issues/388), but is it possible to avoid it?

**Comment by LeFnord** [comment]
would be cool to write a spec (similar to this one: [api_swagger_v2_headers_spec.rb](https://github.com/ruby-grape/grape-swagger/blob/master/spec/swagger_v2/api_swagger_v2_headers_spec.rb)

so it could be reproduced

**Comment by SuperMasterBlasterLaser** [comment]
@LeFnord  If I make that kind of params:

       params do
             requires :arr, type: Array do
                     requires :param1, type: Integer,
                     requires :param2, type: String
             end
       end
       post :handle_post_request do
            {result: params[:arr]}
       end

When I open swagger page. Javascript console shows me this error:

       Uncaught TypeError: Cannot read property '$ref' of undefined

And it does not load my documentation. Do I need to write addidtional info about my array. like this?

       requires :arr, type: Array, documentation: {is_array: true}

**Comment by LeFnord** [comment]
will have a look on it today evening

**Comment by milap-neupane** [comment]
I think there is a similar problem with entities too
```
 expose :array_attr, documentation:
                {
                  type: 'Array',
                  desc: 'Returns array'
                }
```

This throws the same error on the swagger-ui:
```
Uncaught TypeError: Cannot read property '$ref' of undefined
```
When i validated generated JSON, It seems to be missing required property `items`. Or is there something i am missing?
The responded array would be of string `(['string1', 'string2'])`

So it should be generating as the YAML
```YAML
array_attr: 
    type: "array"
    items:
        type: string
```

We need something like this to generate the YAML: 
```
 expose :array_attr, documentation:
                {
                  type: 'Array',
                  desc: 'Returns array',
                  item_type: 'String'
                } 
```

**Comment by SuperMasterBlasterLaser** [comment]
@milap-neupane  Also, The one interesting thing is that when I make accepting type `Array[JSON]` then it will work, however, swagger shows it as **one string field where you must write whole array of JSON**

**Comment by SuperMasterBlasterLaser** [comment]
I have looked to `json` file which grape-swagger generates. When type is set to `Array`, it does not work and it differs from type `Array[JSON]` in accepting parameters:

This when parameters are simple `Array`:

       {  
          "in":"formData",
          "name":"participants[][document_issue_date]",
          "description":"Date when this document was given",
          "type":"array",
          "items":{  
              "type":"date"
          }
          "required":true
          }

This is when parameters are `Array[JSON]`:

         {  
              "in":"formData",
              "name":"participants[document_issue_date]",
              "description":"Date when this document was given",
              "type":"string",
              "format":"date",
              "required":true
           }
It changed structure of date format param field in this Array.

Simple string inside of type `Array`:

            {  
                "in":"formData",
                "name":"participants[][phone]",
                "description":"Phone",
                "type":"array",
                "items":{  
                   "type":"string"
                 },
                "required":true
            }

SImple string inside of type `Array[JSON]`:

           {  
                "in":"formData",
                "name":"participants[phone]",
                "description":"Phone",
                "type":"string",
                "required":true
            }

This completely changes their structure.

**Comment by SuperMasterBlasterLaser** [comment]
Is this problem solved?

**Comment by LeFnord** [comment]
@milap-neupane … have a look on this PR https://github.com/LeFnord/grape-swagger/pull/22, this should solve the `$ref` error
@SuperMasterBlasterLaser …
* your first example (`Array`) is correct, in sense of the spec, means each item must have the same type
* the second (`Array[JSON]`) is a little bit more e complicated, cause the elements of the Array are defined as JSON, which is a complex type, and should have the param_type: `body` with a `schema`
 reference to a `definition` … or?

**Comment by LeFnord** [comment]
@SuperMasterBlasterLaser give actual master a try, this should fix the `$ref` error

**Comment by jonwaghorn** [comment]
Using `master` branch fixes the issue for me.

**Comment by cank** [comment]
I'm having the same issues as @SuperMasterBlasterLaser (I think). master does make the $ref issue go away, but it is still producing incorrect JSON. My params are:

```ruby
        params do
          requires :table_params, type: Hash do
            requires :length, type: Integer
            requires :order, type: Array do
              requires :column, type: Integer
              requires :dir, type: String
            end
            requires :start, type: Integer
            requires :draw, type: Integer
            requires :columns, type: Array do
              requires :data, type: String
              requires :name, type: String
              requires :orderable
              requires :searchable
            end
            requires :search, type: Hash do
              requires :value, type: String
            end
          end
        end
```

The JSON that is produced looks like this (not pasting the whole thing):

```json
          {
            "in": "formData",
            "name": "table_params[][order][][column]",
            "type": "array",
            "items": {
              "type": "integer"
            },
            "required": true
          },
```

What I need it to look like is:

```json
    "postApiV1ExperimentsDatatableTableParams": {
      "type": "object",
      "properties": {
        "columns": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/postApiV1ExperimentsDatatableTableParamsColumns"
          }
        },
```
The good news is that I was able to make a JSON file that works in part by using `Array[JSON]`, which generates the $ref objects correctly, but still doesn't end up with the correct parameters -- each of the items in the nested objects gets typed as an array, and the types for the array objects are listed as '[JSON]'

I've attached the api file that has the parameters listed, and a swagger.json file that I edited manually to get to work with this. I can try to put together a failing spec, assuming that I am doing things correctly.

[swagger.zip](https://github.com/ruby-grape/grape-swagger/files/247793/swagger.zip)

**Comment by LeFnord** [comment]
thanks @cank for the in-depth explanation of the problem …

yeap … your post params should be moved to a definition, this would be achieved be adding `documentation: { in: 'body' }` to the according parameters, see: [api_swagger_v2_param_type_body_spec.rb](https://github.com/ruby-grape/grape-swagger/blob/master/spec/swagger_v2/api_swagger_v2_param_type_body_spec.rb) and [api_swagger_v2_param_type_body_nested_spec.rb](https://github.com/ruby-grape/grape-swagger/blob/master/spec/swagger_v2/api_swagger_v2_param_type_body_nested_spec.rb)

**Comment by SuperMasterBlasterLaser** [comment]
@LeFnord I have checked last version of this gem(Fetched from gihub). Now it problem is solved. Thank you.

**Comment by cank** [comment]
Thanks for the quick reply @LeFnord. I thought all parameters were pushed to the body simply by making the route a `post`, but this makes more sense. Adding `in: 'body'` makes everything work in both the API and UI (yay!), but the generated object definitions in the JSON file are still off -- though, I might be doing something completely wrong:

```ruby
requires :table_params, type: Hash do
  requires :length, type: Integer, documentation: { in: 'body' }
  requires :order, type: Array do
    requires :column, type: Integer, documentation: { in: 'body' }
    requires :dir, type: String, documentation: { in: 'body' }
  end
end
```

Generates:

```json
{
  "paths": {
    "/api/v1/experiments/datatable": {
      "post": {
        "parameters": [
          {
            "name": "postApiV1ExperimentsDatatable",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/postApiV1ExperimentsDatatable"
            }
          }
        ]
      }
    }
  },
  "definitions": {
    "postApiV1ExperimentsDatatable": {
      "type": "object",
      "properties": {
        "table_params": {
          "$ref": "#/definitions/postApiV1ExperimentsDatatableTableParams"
        }
      },
      "description": "Experiments Table"
    },
    "postApiV1ExperimentsDatatableTableParams": {
      "type": "object",
      "properties": {
        "order": {
          "$ref": "#/definitions/postApiV1ExperimentsDatatableTableParamsOrder"
        },
        "length": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "postApiV1ExperimentsDatatableTableParamsOrder": {
      "type": "object",
      "properties": {
        "column": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "dir": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

I need `order` to be an array of objects (sending input like this is what grape is expecting):

```json
    "order": [
      {
        "column": 0,
        "dir": "asc"
      }
    ]
```

So doesn't the corresponding JSON need to look like this?

```json
{
  "order": {
    "type": "array",
    "items": {
      "$ref": "#/definitions/postApiV1ExperimentsDatatableTableParamsOrder"
    }
  },
  "definitions": {
    "postApiV1ExperimentsDatatableTableParamsOrder": {
      "type": "object",
      "properties": {
        "column": {
          "type": "string"
        },
        "dir": {
          "type": "string"
        }
      }
    }
  }
}
```

Note that the `type: array` line gets moved to the parent level, while the children are no longer arrays. Doing this makes the model and model schema shown in swagger UI match the input grape expects.

Thanks again for taking the time to look at this.

**Comment by LeFnord** [comment]
yeap … it should look like it
