### ISSUE TITLE
Question: Document namespaces

### ISSUE THREAD

**Issue by net1957** [ruby-grape/grape-swagger#398]
with this grape definition:
````
        namespace :name1 do
          desc 'name1 desc'
          namespace :op1 do
            desc 'return op1 list'
            get do
              # code to return
            end
          end
          namespace :op2 do
            desc 'return op2 list'
            get do
              # code to return
            end
          end
        end

````
I don't find a way to see the  'name1 desc' in the tag list of swagger UI. I always get "Operations about name1s"
 
in the swagger_doc json i see
````
"tags":[{"name":"name1","description":"Operations about name1s"}, ...]
````
How to give a description to a namespace ?

Regards

**Comment by LeFnord** [comment]
what did you expect?

you can find the generation of the tags here: [tag_name_description.rb](https://github.com/ruby-grape/grape-swagger/blob/master/lib/grape-swagger/doc_methods/tag_name_description.rb)
and for the on path level here: [tag_object](https://github.com/ruby-grape/grape-swagger/blob/master/lib/grape-swagger/endpoint.rb#L187-L189)

it would be fine, if you make a PR to fix the behaviour, thanks
