### ISSUE TITLE
Adding version to path only possible via configuration key 'version'?

### ISSUE THREAD

**Issue by cank** [ruby-grape/grape-swagger#403]
This is for `grape-swagger (0.20.2)`.

Not sure if this is a bug or an undocumented configuration option, but I am unable to get the version to correctly appear in the JSON file under 'paths' unless I do the following:

``` ruby
add_swagger_documentation(
  version: 'v1',
  add_version: true,
)
```

This will produce:

``` json
"paths": {
  "/api/v1/experiments": {
  }
}
```

The configuration instructions in README.md lists `api_version` as a configuration option, but not `version`. This is clearly the intended behavior as shown here:

https://github.com/ruby-grape/grape-swagger/blob/7913a9ecf5856eee2c88992f70cd909b333e92bd/lib/grape-swagger/doc_methods/path_string.rb#L16

and in tests here:

https://github.com/ruby-grape/grape-swagger/blob/master/spec/lib/path_string_spec.rb

Should the documentation be updated to reflect this?

**Comment by dblock** [comment]
Yes definitely. This is probably something that was added recently by @LeFnord. Thanks for contributing!

**Comment by LeFnord** [comment]
thanks for pointing …

**Comment by LeFnord** [comment]
have a look on it … https://github.com/ruby-grape/grape-swagger/pull/405

**Comment by LeFnord** [comment]
corrected behaviour:

* version of the API, also used in a path would be taken from `grape` version
* the documentation version could be set via `doc_version`

this could be confusing, but I think the intention of that is, one have a gem/engine, where the API would be implemented, this could be a semantic version, and should also be documented …

**Comment by BaneOfSerenity** [comment]
the add_swagger_documentation version should be in the upgrade guide as it used to be api_version.

**Comment by dblock** [comment]
@BaneOfSerenity I think you make a good point, would you please contribute?

**Comment by BaneOfSerenity** [comment]
@dblock would be glad to, i should have something by the end of the day. ^.^
