### ISSUE TITLE
Support grape >= 0.14.0 in the 0.20.x series

### ISSUE THREAD

**Issue by glaucocustodio** [ruby-grape/grape-swagger#407]
Is there a specific reason for why grape-swagger v0.20.2 has dependency of `['>= 0.12.0', '<= 0.14.0']`.

I am with the latest grape version (0.16.2) and I can't use it with grape-swagger v0.20.2.

Thanks.

**Comment by dblock** [comment]
The dependency is locked because it doesn't work, @LeFnord is working on some of this, but we would love help!

**Comment by LeFnord** [comment]
check out the repo, unlock the version and use it local
→ it is not tested and you got many deprecation warnings [route.rb#L93](https://github.com/ruby-grape/grape/blob/master/lib/grape/router/route.rb#L93)

**Comment by dblock** [comment]
I've renamed this issue to _Support grape >= 0.14.0 in the 0.20.x series_.

**Comment by dblock** [comment]
HEAD now supports all Grape versions, including 0.16.2. I'd appreciate if some people could try it before I cut a release early next week.
