### ISSUE TITLE
using: with string fails in Entity listed in add_swagger_documentation models:

### ISSUE THREAD

**Issue by dmazan** [ruby-grape/grape-swagger#427]
When you have recursive references to an entity, grape-entity requires that the entity class be specified as a string, rather than as a class constant.  If an entity that uses that convention is specified in the add_swagger_documentation models: option, the result is undefined method 'root_exposures' for the string.  Version 0.20.3.

**Comment by dmazan** [comment]
Same if you list the entity in the entity: option of an endpoint.

**Comment by dblock** [comment]
Try to write a spec that reproduces this?

**Comment by dmazan** [comment]
This simple API definition works and delivers the expected response, formatted according to the locally defined RoleEntity.  Note that `expose :permissions` specifies the `using:` entity as a string, which is permissible and sometimes required.  Retrieving the documentation using Swagger UI works as expected.

```
module BadApi
  class API < Grape::API
    version 'v2', using: :path
    format :json
    prefix :api
    class RoleEntity < Grape::Entity
      expose :id
      expose :display_name
      expose :description
      expose :permissions, using: "Permission::WithoutRole"
    end
    resource :bad do
      desc 'Get a list of roles'
      get '/' do
        present Role.all, with: API::RoleEntity
      end        
    end
    add_swagger_documentation
  end
end
```
Add reference to the entity for documentation purposes by changing the desc line

`desc 'Get a list of roles', entity: API:RoleEntity`

Calling the API still returns the expected response but accessing the documentation using Swagger UI results in the following crash:

```
NoMethodError (undefined method `root_exposures' for "Permission::WithoutRole":String):
  grape-swagger (0.20.3) lib/grape-swagger/endpoint.rb:271:in `expose_params_from_model'
  grape-swagger (0.20.3) lib/grape-swagger/endpoint.rb:240:in `block in parse_response_params'
  grape-swagger (0.20.3) lib/grape-swagger/endpoint.rb:232:in `each'
  grape-swagger (0.20.3) lib/grape-swagger/endpoint.rb:232:in `each_with_object'
  grape-swagger (0.20.3) lib/grape-swagger/endpoint.rb:232:in `parse_response_params'
  grape-swagger (0.20.3) lib/grape-swagger/endpoint.rb:275:in `expose_params_from_model'
  grape-swagger (0.20.3) lib/grape-swagger/endpoint.rb:167:in `block in response_object'
  grape-swagger (0.20.3) lib/grape-swagger/endpoint.rb:163:in `each'
  grape-swagger (0.20.3) lib/grape-swagger/endpoint.rb:163:in `each_with_object'
  grape-swagger (0.20.3) lib/grape-swagger/endpoint.rb:163:in `response_object'
  grape-swagger (0.20.3) lib/grape-swagger/endpoint.rb:110:in `method_object'
  grape-swagger (0.20.3) lib/grape-swagger/endpoint.rb:92:in `block in path_item'
  grape-swagger (0.20.3) lib/grape-swagger/endpoint.rb:86:in `each'
  grape-swagger (0.20.3) lib/grape-swagger/endpoint.rb:86:in `path_item'
  grape-swagger (0.20.3) lib/grape-swagger/endpoint.rb:70:in `block in path_and_definition_objects'
  grape-swagger (0.20.3) lib/grape-swagger/endpoint.rb:68:in `each'
  grape-swagger (0.20.3) lib/grape-swagger/endpoint.rb:68:in `path_and_definition_objects'
  grape-swagger (0.20.3) lib/grape-swagger/doc_methods.rb:55:in `block in setup'

```
The same crash occurs if you change the add_swagger_documentation line to:
`
add_swagger_documentation models: [API::RoleEntity]`

**Comment by LeFnord** [comment]
the `Permission::WithoutRole` entity exist?
and reference it as constant not as string

**Comment by dmazan** [comment]
Yes,` Permission::WithoutRole` exists.  And referencing it as a string, rather than a constant, is supported by grape-entity.  I didn't build the case where reference as a string is necessary, but I can.  If `API::RoleEntity` and `Permission::WithoutRole` both include `using:` any common Entity, both `API::RoleEntity` and `Permissio::WithoutRole` must be specified by string of grape-entity fails.

The relevant grape-entity information is:

#### Exposing with a Presenter

Don't derive your model classes from `Grape::Entity`, expose them using a presenter.

```ruby
expose :replies, using: API::Entities::Status, as: :responses
```

Presenter classes can also be specified in string format, which helps with circular dependencies.

```ruby
expose :replies, using: "API::Entities::Status", as: :responses
```

**Comment by LeFnord** [comment]
Should be fixed with: https://github.com/ruby-grape/grape-swagger/pull/527
