### ISSUE TITLE
Does `base_path` still accept a proc?

### ISSUE THREAD

**Issue by Lordnibbler** [ruby-grape/grape-swagger#429]
Adding grape-swagger to an existing rails project, I want to use a different base path depending on the request host:

```ruby
add_swagger_documentation(
  hide_format: true,
  hide_documentation_path: true,
  base_path: proc { |request| request.host =~ /^api/ ? '/' : '/api' },
)
```

When trying to access the `/docs` route to see my swagger-ui page, I see the following error in Rails:

```sh
NoMethodError (undefined method `host' for nil:NilClass):
  apps/api/lib/myapp/api.rb:43:in `block in <class:API>'
  app/middleware/rack/fix_api_headers.rb:12:in `call'
  app/middleware/rack/geolocation.rb:26:in `call'
  app/middleware/rack/fix_ip_address.rb:43:in `call'
  lib/correlation/rack/timbersaw.rb:14:in `block (2 levels) in call'
  lib/timbersaw.rb:37:in `block in tagged'
  lib/timbersaw/logger.rb:27:in `tagged'
  lib/timbersaw.rb:36:in `tagged'
  lib/correlation/rack/timbersaw.rb:13:in `block in call'
  lib/correlation/rack/timbersaw.rb:12:in `call'
  app/middleware/handle_invalid_percent_encoding.rb:20:in
```

It seems that a request is no longer passed into the `proc` in `base_path`, or am I missing something? Happy to update the documentation with a helpful example if someone can point me in the right direction.

**Comment by LeFnord** [comment]
mmh … use a `lambda` instead and get `request` values from environment
as example, please refer to the specs → [api_swagger_v2_global_configuration_spec.rb](https://github.com/ruby-grape/grape-swagger/blob/master/spec/swagger_v2/api_swagger_v2_global_configuration_spec.rb)

**Comment by dblock** [comment]
Did this use to work? We probably want to support a function that takes `request`, it's a fairly common scenario.

**Comment by LeFnord** [comment]
I agree, but the error here is, that `request`, provided as block param is `nil`,
the question now is, where can the request object can get?

**Comment by Fryie** [comment]
Yes, this used to work: https://github.com/ruby-grape/grape-swagger/blob/6e050fb11081a5352e3521a58fff11205804ea8e/lib/grape-swagger/doc_methods.rb#L304

Then, in [this commit](https://github.com/ruby-grape/grape-swagger/commit/e406abfe3c5344b60c90e41eac16d1e73b46dc9e) (aptly called "update README.md"), basically everything changed, so I don't know what really happened to it.

**Comment by LeFnord** [comment]
@Fryie the swagger spec changed significantly, so to support it we had to change grape-swagger
the functionality was re-added here [optional_object.rb](https://github.com/ruby-grape/grape-swagger/blob/master/lib/grape-swagger/doc_methods/optional_object.rb)

**Comment by Fryie** [comment]
then, possibly, one could replace line 7 with
```
options[key].is_a?(Proc) ? options[key].call(request) : options[key]
```
?

**Comment by dblock** [comment]
@Fryie possibly, try to make a PR with tests?

**Comment by LeFnord** [comment]
@Lordnibbler please give https://github.com/ruby-grape/grape-swagger/pull/441 a try

**Comment by dblock** [comment]
Closing via #441.
