### ISSUE TITLE
Add support for Security Definintions and Requirements

### ISSUE THREAD

**Issue by am17torres** [ruby-grape/grape-swagger#432]
See the spec here.

A list of security definitions
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#securityDefinitionsObject

A security requirement for the whole api
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#securityRequirementObject

Attaching a security requirement to an individual operation within a path
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operationObject

Proposing something like this:

```ruby

# for defining the security definitions
add_swagger_documentation format: :json,
          doc_version: '23',
          schemes: 'https',
          host: -> { 'another.host.com' },
          base_path: -> { 'somewhere/over/the/rainbow' },
          mount_path: 'documentation',
          add_base_path: true,
          add_version: true
# specify the security definitions
          securityDefinitions: {
            api_key: {
              type: "apiKey",
              name: "api_key",
              in: "header"
            },
            petstore_auth: {
              type: "oauth2"
              authorizationUrl: "http://swagger.io/api/oauth/dialog"
              flow: "implicit"
              scopes: {
                write:pets: "modify pets in your account"
                read:pets: "read your pets"
              }
            }
          }
# specify security that applies to the whole document
          security: {
             api_key: [],
             petstore_auth: ['read:pets']
          }

# for a security requirement to a path operation
  desc 'This returns something',
    failure: [{ code: 400, message: 'NotFound' }]
    security: {
      api_key:[],
      petstore_auth:['read:pets']
    }
  params do
      requires :foo, type: Integer
   end
      get :configuration do
        { 'declared_params' => declared(params) }
      end
```

**Comment by dblock** [comment]
It would be great if this kind of extension was a thirdparty gem. It will likely need work in this project to enable that.

**Comment by LeFnord** [comment]
@am17torres your proposal looks good, please feel free to make a PR
@dblock think we should implement the parts of the spec first, and then if single parts are growing, move it out into single gems
I'm personally not a big fan of having for each simple functionality a gem, this could open up the dependency hell very quickly, especially if the project is a bigger one and/or more then a handful of devs are working on (e.g. our app uses more then 200 gems, the half of them are own ones, and more then 100 people working on 😉)

**Comment by dimitertodorov** [comment]
Interested in this. Has anyone started work on a fork that addresses this?

**Comment by LeFnord** [comment]
@dimitertodorov … I think that at the moment nobody started :(

**Comment by LeFnord** [comment]
btw, there is always a configuration key to add it (https://github.com/ruby-grape/grape-swagger/blob/master/lib/grape-swagger/doc_methods.rb#L104) ≥ but was not re-implmented yet
