### ISSUE TITLE
override type with documentation parameter

### ISSUE THREAD

**Issue by scauglog** [ruby-grape/grape-swagger#443]
multi types seems not well supported, so I would like to use documentation hash to specify which type the documentation should use. for example
```ruby
params do
  optional :filters, types: [JSON, Hash], desc: "json format", documentation: { type: "json"}
end
   post "private/:module_name/:method_name" do
end
```

So I modified in `lib/grape-swagger/doc_methods/parse_params` the "call" method (line 9 to 13)

before
```ruby
data_type = GrapeSwagger::DocMethods::DataType.call(settings)
additional_documentation = settings[:documentation]
if additional_documentation
  settings = additional_documentation.merge(settings)
end
```

after
``` ruby
additional_documentation = settings.fetch(:documentation, {})
settings.merge!(additional_documentation)
data_type = GrapeSwagger::DocMethods::DataType.call(settings)
```

this work for me. But maybe there is a good reason to merge settings in documentation or to do this merge after calling DataType.

(edit: you shouldn't delete the documentation key after merging)

**Comment by LeFnord** [comment]
@scauglog … yeap, multi types are not supported at the moment
please make a proposal, how it could be documented in with swagger,
and validate it against http://bigstickcarpet.com/swagger-parser/www/index.html

I didn't found a solution yet, but maybe you?

**Comment by scauglog** [comment]
[swagger don't allow multi type](https://github.com/OAI/OpenAPI-Specification/issues/458). But we could allow user to specify the type they prefer when generating the doc or select the first type provided in the Array as the type or both.

**Comment by LeFnord** [comment]
@scauglog … yeap I know, that's why again … make a proposal as PR 😉

**Comment by scauglog** [comment]
I noticed that according to the readme the default value provided in the documentation hash override the grape default `Note that the example value will override the Grape default value.` currently this doesn't work but with my fix it will.

**Comment by LeFnord** [comment]
https://github.com/ruby-grape/grape-swagger/pull/444 solved it
