### ISSUE TITLE
Why are Hashes not included?

### ISSUE THREAD

**Issue by aschuster3** [ruby-grape/grape-swagger#445]
While parsing through to see why my Hash was not appearing, I found this line: https://github.com/ruby-grape/grape-swagger/blob/master/lib/grape-swagger/endpoint.rb#L234

Basically, when that line says that if a parameter is a Hash, it will not be included.  In a personal branch, I changed the logic to read as follows (emphasis on the added parenthesis):
```ruby
memo[key] = param.last unless (param.last[:type] == 'Hash' || param.last[:type] == 'Array') && !param.last.key?(:documentation)
```
This makes it so that a Hash or an Array is not included if it is not documented instead of not including Hashes ever.  Before I make a PR upstream, I was curious if this was intentional.  I'm using this in conjunction with `grape-entity` and the problem I faced was when I call `ObjectEntity.documentation` as a required param like as follows:
```ruby
params do
  requires :something, using: ObjectEntity.documentation
end
```
With `ObjectEntity` looking like this:
```ruby
class ObjectEntity < Grape::Entity
  expose :object_id, documentation: { type: Integer, documentation: { in: 'body' } }
  expose :object_hash, documentation: { type: Hash, documentation: { in: 'body' } }
end
```
The `object_id` appears just fine, but the `object_hash` does not.

It is worth mentioning that if I state my parameters as follows, it works fine, but doesn't let me have path paramenters appear as I would prefer:
```ruby
desc 'Sample description' do
  params ObjectEntity.documentation
end
```

I'm using the Master branch of `grape-swagger` with all dependencies updated to the latest versions.

**Comment by dblock** [comment]
I would say that if there's no spec for it, it's not intentional.

**Comment by dblock** [comment]
Does #454 address everything? Closing.

**Comment by aschuster3** [comment]
Yep!
