### ISSUE TITLE
swagger-ui doesn't render the endpoints if method[:description] is deleted

### ISSUE THREAD

**Issue by texpert** [ruby-grape/grape-swagger#449]
It shows 'http://xxxxxx.ngrok.io/api/swagger_doc; Please wait.' and doesn't go further.

As a workaround I tried to replace the string https://github.com/LeFnord/grape-swagger/blob/3e747e3e221e2421d912ede97eebd29845867054/lib/grape-swagger/endpoint.rb#L114

with

```
    method.delete_if do |key, value|
      next if key == :description
      value.blank?
    end
```
and then everything is OK. 

Though I am not satisfied because the behaviour of not rendering is not 100% reproducible - there are some routes which are going without description, and some, which are causing the pause. 

Any hints what else should be checked?

**Comment by texpert** [comment]
BTW, commenting the 114 string resolves the issue too. Maybe no need to delete methods with empty values at all?

**Comment by LeFnord** [comment]
hi @texpert …
please don't refer to my branch, use the official master instead, cause it is always a WIP fork, thanks

the described behavior was added here https://github.com/ruby-grape/grape-swagger/issues/401,
means it corresponds with the spec, where the description of a operation object isn't required,
it seems that it is a swagger UI bug not a grape-swagger

**Comment by texpert** [comment]
Think, though, I've found the cause here - https://github.com/ruby-grape/grape-swagger/blob/master/lib/grape-swagger/doc_methods/move_params.rb#L44

Changing this line to not add the description if it is missing
```
@definitions[name][:description] = path[:description] if path[:description]
```
make the rendering to work OK.

**Comment by LeFnord** [comment]
cool @texpert … it seems you found it, pleas could you make a PR for that, thanks

**Comment by texpert** [comment]
Sure - there's the PR - https://github.com/ruby-grape/grape-swagger/pull/450
