### ISSUE TITLE
DELETE and return 200 OK

### ISSUE THREAD

**Issue by dopykuh** [ruby-grape/grape-swagger#459]
I want to return a 200 OK on DELETE method. 
I also written a http_codes entry for this, but this won't work. 
https://github.com/ruby-grape/grape-swagger/blob/master/lib/grape-swagger/endpoint.rb#L178-L181

**Comment by dblock** [comment]
That code definitely looks suspicious. Maybe write a spec that reproduces it first?

**Comment by LeFnord** [comment]
please see this explanation https://github.com/ruby-grape/grape-swagger/pull/440#issuecomment-222302039

**Comment by LeFnord** [comment]
@dopykuh … could it be closed?
