### ISSUE TITLE
Can't override nickname when using namespaces and route params

### ISSUE THREAD

**Issue by pbendersky** [ruby-grape/grape-swagger#481]
I have the following API end-point:
```
    class Products < Grape::API
      namespace :products do
        route_param :product_id, type: Integer
          desc 'Return a given product by id.', nickname: 'getProductById'
          get do
          end
        end
      end
    end
```
In this case, overriding the `nickname` doesn't work and I get the auto-generated one. Any idea? I'm using `grape-swagger` 0.22.

**Comment by LeFnord** [comment]
@pbendersky … sorry, this isn't re-implemented yet

**Comment by pbendersky** [comment]
@LeFnord any pointer on where to look to contribute it?

**Comment by LeFnord** [comment]
yeap, this method https://github.com/ruby-grape/grape-swagger/blob/master/lib/grape-swagger/endpoint.rb#L203-L205 is responsible for the tags on method level and would be used here https://github.com/ruby-grape/grape-swagger/blob/master/lib/grape-swagger/endpoint.rb#L112
