### ISSUE TITLE
How can I define required items in model?

### ISSUE THREAD

**Issue by alingogo** [ruby-grape/grape-swagger#484]
In [petstore](http://petstore.swagger.io/?baseUrl=http%3A%2F%2Fpetstore.swagger.io%2Fv1%2Fswagger.json#!/pet/getPetById), "required" can be used in model. But, when using grape + grape-enitiy + grape-swagger, if I set "required" in documentation like using in params, it can not show "required" items(however, show "optional"). 

```
Pet {
id (integer, optional),
category (Category, optional),
name (string),
photoUrls (Array[string]),
```
* name, photoUrls are not "optional", they are defined to required by json like:

```
"Pet":{"type":"object","required":["name","photoUrls"],"properties":{"id":{"type":"integer","format":"int64"},"category":
```

question:
  How can I define required item in model?(not show "optional")

(when I see your newest source code, this question are not fixed perhaps)

**Comment by dblock** [comment]
I am not sure what the answer is, but I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions, I am sure you'll get an answer there.
