### ISSUE TITLE
Export swagger JSON to file

### ISSUE THREAD

**Issue by bmedici** [ruby-grape/grape-swagger#496]
I've searched a bit on the documentation and open issues, and did not find much about that.

It would be great to be able to generate a static JSON file from Grape, instead of just exposing it on a mount point. Interfaced with a rake task, we could automatically document the current API to a static file, and commit it in the repository.

For now, the only solution I've found is to launch the whole project, query the URL and save the result to a file. It's a bit overkill :)

Any suggestion and opinion for this kind of feature ?

Thanks !

Bruno

**Comment by LeFnord** [comment]
yeap, this is in principal a good idea, the only downcase I see, is that every API could have a different name, could be mounted somewhere, etc … so a general solution isn't so easy as expected

maybe you could have a look on this [rake tasks](https://github.com/LeFnord/grape-api-starter/blob/master/lib/starter/rake/grape_tasks.rb) and using it as inspiration for a PR 😉

**Comment by LeFnord** [comment]
solved here: https://github.com/ruby-grape/grape-swagger/pull/500
