### ISSUE TITLE
base_path missing

### ISSUE THREAD

**Issue by boomshadow** [ruby-grape/grape-swagger#498]
I'm using `ReDoc` to view the Swagger output from `grape-swagger`. It was continually showing my endpoints as:

    http://127.0.0.1:9292undefined/v1/list

This seems to be an issue with `grape-swagger`. The only way to fix this was to specifically define the base_path, even though I'm not adding it:

    add_swagger_documentation \
        base_path: '/',
        add_base_path: false

I'm using grape-swagger `v0.23.0`

**Comment by LeFnord** [comment]
@boomshadow … this isn't a grape-swagger issue (`basePath` isn't required)
→ this PR [#102](https://github.com/Rebilly/ReDoc/pull/102) should be fixing it
