### ISSUE TITLE
Header parameters for GET requests

### ISSUE THREAD

**Issue by stlewis** [ruby-grape/grape-swagger#499]
I have the following sitting inside of the `desc` blocks for both of my API endpoints:

``` ruby
headers XAuthToken: {description: "The API Authentication Token for your user", required: true}, XAuthKey: {description: "The API Authentication Key for your user", required: true}
```

One of my endpoints is a POST, the other is a GET. The swagger doc generates a field for the header parameters in the POST request, but not in the GET request. Am I missing something?

**Comment by anakinj** [comment]
@stlewis What version of grape-swagger where you using, have you tried the latest version? I had some similar issues with headers not being included in some cases. #494 fixes the issue I was struggling with.

**Comment by LeFnord** [comment]
it seems to be fixed …
