### ISSUE TITLE
Example value feature is broken in swagger ui for body parameters

### ISSUE THREAD

**Issue by serggl** [ruby-grape/grape-swagger#507]
In particular it is broken for parameters which data type is `Grape::Entity`

Here is a maple API and entities definition:
```ruby
class Rest::Sales::Root < Grape::API
  prefix :sales

  version 'v1', using: :path

  module Entities
    class A < Grape::Entity
      expose :a, documentation: {type: 'string'}
      expose :b, documentation: {type: 'number'}
    end
  end

  desc 'Create a new something' do
    success Entities::A
  end

  params do
    optional :data, type: Entities::A
  end

  post 'something' do
    {}
  end

  add_swagger_documentation hide_documentation_path: true, add_version: true, models: [Entities::A]
end
```

And here is how it looks like in swagger:

<img width="967" alt="2016-09-29 16 24 10" src="https://cloud.githubusercontent.com/assets/53304/18956004/7523439e-8662-11e6-8ed5-fc822c846f97.png">

<img width="967" alt="2016-09-29 16 25 00" src="https://cloud.githubusercontent.com/assets/53304/18956009/7e1c4de2-8662-11e6-9554-6eb43b47693c.png">

One the last screenshot you can also notice that data type names are quite different, but they should represent the same type.

Here is a swagger json generated for this API class:
```json
{
	"info": {
		"title": "API title",
		"version": "0.0.1"
	},
	"swagger": "2.0",
	"produces": [
		"application/json"
	],
	"host": "localhost:3000",
	"basePath": "/api",
	"tags": [
		{
			"name": "something",
			"description": "Operations about somethings"
		}
	],
	"paths": {
		"/sales/v1/something": {
			"post": {
				"summary": "Create a new something",
				"description": "Create a new something",
				"produces": [
					"application/json"
				],
				"consumes": [
					"application/json"
				],
				"parameters": [
					{
						"name": "SalesV1Something",
						"in": "body",
						"required": true,
						"schema": {
							"$ref": "#/definitions/postSalesV1Something"
						}
					}
				],
				"responses": {
					"201": {
						"description": "Create a new something",
						"schema": {
							"$ref": "#/definitions/A"
						}
					}
				},
				"tags": [
					"something"
				],
				"operationId": "postSalesV1Something"
			}
		}
	},
	"definitions": {
		"postSalesV1Something": {
			"type": "object",
			"properties": {
				"data": {
					"type": "Rest::Sales::Root::A"
				}
			},
			"description": "Create a new something"
		},
		"A": {
			"type": "object",
			"properties": {
				"a": {
					"type": "string"
				},
				"b": {
					"type": "number"
				}
			},
			"description": "Create a new something"
		}
	}
}
```

Seems like a proper data type link should be `"$ref": "#/definitions/A"` instead of `"type": "Rest::Sales::Root::A"`

**Comment by LeFnord** [comment]
@serggl … mmh, think it has to do with the `model_name` stuff you commented, did it behaves same, if you remove the `model` parameter on `add_swagger_documentation`?

**Comment by serggl** [comment]
yes @LeFnord. Actually after looking into source code, I can suggest that it has nothing to do with the `models` option, which is a bit useless since it adds records to `definitions` section of the output json after everything (request/response/parameters objects) was parsed. PR is on the way..

**Comment by serggl** [comment]
here is the PR for this #511
