### ISSUE TITLE
Show list of strings that are enums in Model tab in Swagger UI

### ISSUE THREAD

**Issue by WojciechKo** [ruby-grape/grape-swagger#522]
Is it possible to generate list o enums in documentation?
I've tried to use forked https://github.com/ruby-grape/grape-swagger-entity and create that:
```
class Entities::Result < Grape::Entity
  expose :modes,
         values: ['driving', 'train'],
         documentation: { is_array: true,
                          desc: 'Transport modes'}
end
```
this gives me
```
definitions: {
  Result: {
    type: "object",
    modes: {
      type: "array",
      items: {
        type: "string",
        enum: ["driving", "train"]
      },
      description: "Transport modes"
    }
  },
  ...
}
```
And it seems to be correct but on Swagger UI I see:
`Model`: 
```
Result {
  modes (Array[string]): Transport modes
}
```
`Example Value`
```
{
  "modes": ["driving"]
}
```

# Question:
Am I doing something wrong?
How can In indicate in `Model` that array `mode` can have one of those value: `['driving'] || ['train'] || ['driving', 'train']`

**Comment by LeFnord** [comment]
@WojciechKo … it looks good to me, can you validate the generate swagger? -> see the [rake tasks](https://github.com/ruby-grape/grape-swagger#rake) for it, to be sure it is valid

**Comment by WojciechKo** [comment]
Maybe it's valid but swagger ui still doesn't show me possible entries for `model`.
Do you know how can I achieve that?

**Comment by WojciechKo** [comment]
Obviously it wasn't problem of `grape-swagger`
Little fix to swagger-ui works fine :)
