### ISSUE TITLE
Error when entity must be specified as a string

### ISSUE THREAD

**Issue by dmazan** [ruby-grape/grape-swagger#525]
Under some circumstances when exposing an association using an entity, the entity must be specified as a string.  In that case, if grape-swagger-entity is also used, grape-swagger fails with the following error:

undefined method `ancestors' for "Permission::WithoutRoleEntity":String
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-swagger-0.24.0/lib/grape-swagger/endpoint.rb:275:in`block in expose_params_from_model'

Currently fixed locally with a monkey patch to the`expose_params_from_model` method:

```
def expose_params_from_model(model)
  model = model.constantize if model.is_a? String
  model_name =model_name(model)
  .
  .
  .
```

**Comment by LeFnord** [comment]
@dmazan … please can you provide some more informations, a PR would be best including you fix …

**Comment by LeFnord** [comment]
seems realted to: https://github.com/ruby-grape/grape-swagger/issues/427

**Comment by LeFnord** [comment]
Should be fixed with: https://github.com/ruby-grape/grape-swagger/pull/527

**Comment by LeFnord** [comment]
@dmazan … thanks for the fix
