### ISSUE TITLE
Is it possible to export static HTML or Md ?

### ISSUE THREAD

**Issue by c0ze** [ruby-grape/grape-swagger#526]
Sorry, new to swagger. Is it possible to export swagger doc to some kind of static document ?
Or is there another tool which does what I want ?

**Comment by LeFnord** [comment]
@c0ze … try to use the [rake task](https://github.com/ruby-grape/grape-swagger#rake-tasks) to get the json as static file and transform it to your needs

**Comment by c0ze** [comment]
I am sorry, usage of the rake task is not very clear.

```
require 'grape-swagger/rake/oapi_tasks'
GrapeSwagger::Rake::OapiTasks.new(::Api::Base)
```

gives me a `GrapeSwagger::Rake::OapiTasks` object. what should I do with this ?

As for the other part of my original question, I managed to use [bootprint-openapi](https://github.com/bootprint/bootprint-openapi) to get the static html for my swagger. I don't want to depend on a running server to get the doc though, making the rake task spit out json will greatly solve my problem. My ultimate goal is to produce swagger / openapi docs via CI.

**Comment by LeFnord** [comment]
hi @c0ze … put this to lines into the Rakefile of you app/api and adept the argument to your specific one, then run `rake oapi:fetch`

**Comment by lostie** [comment]
I'm using the following versions on a Rails app:

```
bundle list
  * rails (5.2.1.1)
  * grape (1.2.1)
  * grape-swagger (0.32.0)
```

This is the content of my Rakefile:

```ruby
require_relative 'config/application'

Rails.application.load_tasks

require 'grape-swagger/rake/oapi_tasks'

require 'api/root'
GrapeSwagger::Rake::OapiTasks.new(::API::Root)
```

but when I try and list the tasks I get the following error:

```shell
bundle exec rake -vT
rake aborted!
LoadError: cannot load such file -- api/root
```

I debugged the problem further and understand that this happens because the `$LOAD_PATH` (when executing the rake task) does not include the directories that Rails normally autoloads when booting the app, it just has 'RAILS_ROOT/lib' and the directories for the gems that it depends on.

Was this setup working in previous Rails versions? Do you have any recommendation to solve this issue?

**Comment by LeFnord** [comment]
Hi @lostie … yeap, the setup worked and it is independend from rails …

your error says `LoadError: cannot load such file -- api/root`,  
this is based on your `require 'api/root'` and not on the task itself

in a standard grape/rails setup, mean under app/api the loading should be working  
without require and your base api class as argument

**Comment by lostie** [comment]
@LeFnord I understand what you're saying about being independent from Rails, but when I execute `bundle exec rake -vT` (local console, so development mode) only `lib` is in the load path, so I'm not following how come in your case you don't even need the `require`, as the API code is not accessible at this stage. 😕 

FYI, in my case the API base class is `API::Root` and it's placed under `app/controllers/api/root.rb` which seems to be working fine when I boot the app or when I access that class in the rails console.

```ruby
# Rakefile

require_relative 'config/application'

binding.pry
Rails.application.load_tasks

[1] pry(main)> $LOAD_PATH
=> ["<APP_ROOT>/lib",
 "/usr/local/Cellar/rbenv/1.1.1/rbenv.d/exec/gem-rehash",
 "<HOME_DIR>/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib",
 "<HOME_DIR>/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/web-console-3.7.0/lib",
...
 "<HOME_DIR>/.rbenv/versions/2.5.3/lib/ruby/2.5.0",
 "<HOME_DIR>/.rbenv/versions/2.5.3/lib/ruby/2.5.0/x86_64-darwin18"]
```

My understanding, and it's the reason I was attempting to use the require, is that I need to have the source code available in the $LOAD_PATH and either require it or autoloaded, which neither seems to be in place.

PS: Even when I have follow the setup as describe [here](https://github.com/ruby-grape/grape#rails) placing all the code in `app/api` and  setting the `autoload_paths` I get exactly the same output in the  `$LOAD_PATH`, meaning the code is not available. 

Am I missing something obvious here? 

Out of interest, is your Rails 5.X app been upgraded from 4.X? Mine is a new 5.X and has the following  settings for eager load:

```ruby
config/environments/production.rb|11 col 10| config.eager_load = true
config/environments/development.rb|10 col 10| config.eager_load = false
config/environments/test.rb|13 col 10| config.eager_load = false
```
