### ISSUE TITLE
Default status code not exposed

### ISSUE THREAD

**Issue by migmartri** [ruby-grape/grape-swagger#533]
Hi,

As explained [here](https://github.com/ruby-grape/grape#http-status-code), in Grape you can change the default status code using the `status` method.

Example
```ruby
post :foo do
  status 202 
end
```

This makes grape return 202 fine, but the new value does not get exposed in the Swagger documentation.

I have tried using `http_codes` but it just adds extra status codes not changing the default one.

Thanks, 
Miguel

**Comment by LeFnord** [comment]
@migmartri  please have a look here, actual it could be done, but it is not documented yet

**Comment by LeFnord** [comment]
sorry, @migmartri was a bit to quick, this solution didn't respect the success entity, so the issue is still open

**Comment by LeFnord** [comment]
wow, it looks strange 😉 …

**Comment by LeFnord** [comment]
and yeap, @migmartri give it a try

**Comment by migmartri** [comment]
@LeFnord that was fast! It works!

Below you can see how I have applied your change using the long block version of the documentation instead of the inline one.

Thanks again.

Regards,
Miguel

```ruby
  desc 'Deploy a cloud formation stack.' do
    detail 'Instantiate a cloud formation stack providing a template'
    success(code: 202, model: API::V1::Entities::Operation,
                  message: 'The operation has been queued')
  end
```
