### ISSUE TITLE
Support setting custom :format value 

### ISSUE THREAD

**Issue by migmartri** [ruby-grape/grape-swagger#536]
Hi,

Currently, in grape-swagger, the value of `:format` and `:type` gets implied by `documentation.type`

i.e.

```ruby
  requires :input, type: String, documentation: { type: 'integer' }
``` 

Grape-swagger then, will use an internal mapping to find Swagger [type, format] pairs (please note that the `type` value in the documentation Hash actually matches the `format` value in the Swagger Spec instead.

So taking into account the example `documentation: { type: 'FOO }`

* If FOO is one of the mapped formats (`PRIMITIVE_MAPPINGS` constant), the library will generate a parameters/properties payload with type and format.
* if FOO is not a known format. The library will return type = FOO and format = nil

I think that although we might want to keep the current mapping for convenience, we should add the possibility of override the `format` value. Since according to the OpenAPI [spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types), `format` is a free form value used for documentation purposes.

>Primitives have an optional modifier property format. Swagger uses several known formats to more finely define the data type being used. However, the format property is an **open string-valued property**, and can have any value to support documentation needs.

i.e

```
documentation: { type: 'string', format: 'myFormat' }? 
```  

What do you think,

Regards,
Miguel

**Comment by LeFnord** [comment]
sounds good to me, but we should add a section in the README with the link to the [swagger mapping](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/2.0.md#data-types), so one can see what is possible

**Comment by LeFnord** [comment]
@migmartri would be nice, if you could update your https://github.com/ruby-grape/grape-swagger/pull/531 accordingly

**Comment by LeFnord** [comment]
sorry @migmartri for confusing, but I read your comment here first, and then the other one

**Comment by LeFnord** [comment]
it is implmeneted here: https://github.com/ruby-grape/grape-swagger-entity/pull/21 and https://github.com/ruby-grape/grape-swagger/pull/576
