### ISSUE TITLE
Enum values not shown in Swagger entity definitions

### ISSUE THREAD

**Issue by migmartri** [ruby-grape/grape-swagger#537]
Hi,

When I add a set of values to an entity property `documentation.values` it does not get exposed to the Swagger spec via `definitions.[MyEntity].properties.[MyProperty].enum`.

For example:

Having this entity:
```ruby
module API::V1
  module Entities
    class TestEntity < Grape::Entity
      expose :test_property, documentation: { values: [:foo, :bar] }
    end
  end
end
```

And referencing it from the using the success documentation method.

```ruby
module API
  module V1
    class Test < Grape::API
      resource :test_resource do
        desc 'Test resource' do
          success API::V1::Entities::TestEntity
        end

        get  do
        end
      end
    end
  end
end

```

It generates the following Swagger spec which does not include the `enum` array in the `TestEntity`.

```json
{
   "paths":{
      "/v1/test_resource":{
         "get":{
            "summary":"Test resource",
            "description":"Test resource",
            "produces":[
               "application/json"
            ],
            "responses":{
               "200":{
                  "description":"Test resource",
                  "schema":{
                     "$ref":"#/definitions/TestEntity"
                  }
               }
            },
            "tags":[
               "test_resource"
            ],
            "operationId":"getV1TestResource"
         }
      }
   },
   "definitions":{
      "TestEntity":{
         "type":"object",
         "properties":{
            "test_property":{
               "type":"string"
            }
         },
         "description":"Test resource"
      }
   }
}
```

Adding enum in an entity definition is valid Swagger/OpenAPI spec and compatible with SwaggerUI as well as you can see in the screenshot below which is using a manually modified json spec.

![selection_041](https://cloud.githubusercontent.com/assets/24523/20609102/4edaa482-b23d-11e6-8d43-f77ec01a8b4a.png)
 
Please note that enums seems to be supported when used as part of parameters definitions doing something like,

```ruby
  params do
    requires :all, using: API::V1::Entities::TestEntity.documentation
  end
```

but the values are still not added in the Swagger entity definition itself.

- [x] Support enum exposure using Grape entities `documentation.values`

Thanks,
Miguel

**Comment by LeFnord** [comment]
@migmartri … done here https://github.com/ruby-grape/grape-swagger-entity/pull/8
see also this spec: https://github.com/ruby-grape/grape-swagger/pull/575
