### ISSUE TITLE
grape 'array' type not compatible with swagger ? 

### ISSUE THREAD

**Issue by pigghost** [ruby-grape/grape-swagger#542]
here is my parameter description of Grape API:

```
params do
      requires :logs, type: Array, documentation: {param_type: 'body'}
end
```
and below is the result using 'grape-swagger' and swagger-ui:
```
[
  {
    "logs": "string"
  }
]
```
obviously, it's not correct. Seems a bug?

**Comment by LeFnord** [comment]
pleHi @pigghost … yeap there was a bug in 0.25.1, but not only, youe to specify a type for the array, if you want to use it this way, see: [542_array_of_type_in_post_body_spec.rb](https://github.com/ruby-grape/grape-swagger/blob/ca1f35eb59b8dc820ca42edc8aea52c172e3c2db/spec/issues/542_array_of_type_in_post_body_spec.rb#L10)
