### ISSUE TITLE
Can't define an entity field as having 'any' type.

### ISSUE THREAD

**Issue by james-w** [ruby-grape/grape-swagger#545]
I wish to define a field of one of my responses as having 'any' type. It's an 'extra' field
in errors that has some extra structured information that depends on the error.

I believe the way to do this in JSON schema is to omit the 'type' declaration for that
field, but I don't believe that is possible with grape-swagger.

Specifically

    class SomeEntity < Grape::Entity
       expose :extra,
                    documentation: {
                      type: <ANY>
                    }
    end

I'm not sure what the best way to declare this would be.

(I filed this here as despite me using grape-entity, I believe it is this project that generates the swagger for this, rather than grape-swagger-entity)

Thanks,

James

**Comment by LeFnord** [comment]
@james-w … please refer to the [OAPI spec](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/2.0.md#data-types), there a type of `any` isn't foreseen.

OAPI/swagger is based on JSON spec, but differs in some points

think on, you have an API, where some elements of the response have no/any datatype,
and now a consumer of your API (maybe it is written in C), how should the consumer be handle the response? By given a type of `any` the consumer has to implement additional logic to find out what for type it is.

But to achieve a similar behaviour, I would be suggesting to set the type to `string`.

**Comment by james-w** [comment]
Hi, I hadn't notice that the Swagger spec restricted the types in that manner.

I see there is some discussion in the swagger bugtracker about changing this a bit.

I have some disagreement with their rationale for this, but it is what it is.

Thanks for your time.

James

**Comment by LeFnord** [comment]
feel free to be a part of the discussion and introduce results here 😉
