### ISSUE TITLE
Included example App is broken

### ISSUE THREAD

**Issue by tamaloa** [ruby-grape/grape-swagger#548]
With ruby 2.3.1 after starting the example application an opening http://localhost:9292/swagger_doc following error occurs:

    GrapeSwagger::Errors::UnregisteredParser at /swagger_doc
    No parser registered for Splines.

**Comment by LeFnord** [comment]
Hi @tamaloa … yeap, it is known, try to use [grape-starter](https://github.com/LeFnord/grape-starter) instead

**Comment by dblock** [comment]
@LeFnord you know about [gris](https://github.com/artsy/gris)? It's a fairly complete api generator.

**Comment by LeFnord** [comment]
@tamaloa … mmh, it seems it isn't, I played around and all is fine, run it with: `bundle exec rackup`
