### ISSUE TITLE
Nullable type

### ISSUE THREAD

**Issue by migmartri** [ruby-grape/grape-swagger#550]
Hi,

Swagger's OpenApi [data types](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types) are based on  json schema draft 4 which seems to support nullable values.

This means that you can allow a property to be `null` and still validate by doing:

```json
"service": {
    "type": "object",
      "properties": {
        "name": {
          "type": ["string", "null"],
          "description": "Service name"
        }
    }
  }
``` 

Currently, grape-swagger, in the scenario of multiple types, takes the first one so the example above is not possible. 

It would be great if we could support multiple types in the case of being the `null` primitive. 

This will make validation tools like [apivore](https://github.com/westfieldlabs/apivore) work out of the box with grape-swagger and grape-entity since they do not accept `null` returned values unless explicitly marked in the swagger spec. 

Thoughts?

**Comment by Bugagazavr** [comment]
Hello, multiple types can be a `["string", "integer"]` for example, not only nullable types, is this correct?

**Comment by LeFnord** [comment]
Hi @migmartri … think the actual OAPI spec didn't support it, see: https://github.com/OAI/OpenAPI-Specification/issues/229, if you are following the discussion – I didn't read it completely, sorry no time – then there are pros and cons listed, and I belive the next version of it would allow

**Comment by migmartri** [comment]
@LeFnord, @Bugagazavr thanks for the responses.

I see, I guess that I got confused by the different specs so I appreciate the clarification. 

I guess that for now I'll opt for hiding the attributes that can return null in the entities so it validates against the Swagger schema.

Thanks again,
Miguel

**Comment by LeFnord** [comment]
yeap, it seems so, but I encourage you to commit to the OAPI spec 😉

**Comment by bogdan** [comment]
It was hard to find the solution, leaving a comment here:

```
  expose :lens, documentation: { type: String, x: {nullable: true} }
```

Adds `x-nullable: true` field that de-facto standard for Swagger 2.0: 
https://redocly.com/docs-legacy/api-reference-docs/specification-extensions/x-nullable
