### ISSUE TITLE
Endpoint description containts HTML in place of markdown

### ISSUE THREAD

**Issue by frodrigo** [ruby-grape/grape-swagger#559]
Like main info description, endoint description should be in markdown and not in HTML

This line should be fixed or removed
https://github.com/ruby-grape/grape-swagger/blob/master/lib/grape-swagger/endpoint.rb#L138

As side question, I think there is no raison to add again the summary in the description (and more over as a title)
https://github.com/ruby-grape/grape-swagger/blob/master/lib/grape-swagger/endpoint.rb#L136

**Comment by dblock** [comment]
@frodrigo write a test, make a PR?

**Comment by LeFnord** [comment]
closed with follow-up issue #566
