### ISSUE TITLE
Cannot use `:version` in a route

### ISSUE THREAD

**Issue by justincampbell** [ruby-grape/grape-swagger#563]
I am trying to describe the following URL structure:

```rb
namespace 'versions' do
  desc "List all versions"
  get

  namespace ':version' do
    desc "Get details about a version
    get
  end
end
```

Which I expect to make these URLs:

```
/versions              List all versions
/versions/{version}    Get details about a version
```

But what ends up being show in Swagger UI/swagger_doc JSON is:

```
/versions              List all versions
/versions              Get details about a version
```

I believe this is because of this code: https://github.com/ruby-grape/grape-swagger/blob/5001a64817df78f277b4de67da215bd0f0d3b203/lib/grape-swagger/doc_methods/path_string.rb#L22

I'm not using path versioning. Is there a way to turn this off? Or maybe could Grape and Grape-Swagger use a more specific name (such as `{__version}`) to avoid collisions?

**Comment by LeFnord** [comment]
Hi @justincampbell … mmh, the problem is, that `version` itself  is a reserved word, and yeah the place you pointed to, there the version will be set, if one was given, but will be build here https://github.com/ruby-grape/grape-swagger/blob/master/lib/grape-swagger.rb

I think you can achieve what you want very simple, without any changes in grape, or grape-swagger, by using `version` as a parameter, and this is what you want, something like this:
```ruby
namespace :versions do
  desc 'get all of versions',
       is_array: true
  get do
    # your code goes here
  end

  desc 'get specific version'
  params do
    requires :version
  end
  get ':version' do
    # your code goes here
    present :params, params
  end
end
```

**Comment by LeFnord** [comment]
another version to achieve it, is:
```ruby
resource :versions do
  desc 'List all version'
  get do
    { params: params }
  end
  
  route_param :version do
    desc 'Lists a single version'
    get do
      { params: params }
    end
  end
end
```

**Comment by justincampbell** [comment]
Thanks! I'll try those out.

**Comment by LeFnord** [comment]
please have in mind, this is only a fix, cause route params actual are not supported, see: https://github.com/ruby-grape/grape-swagger/issues/532
