### ISSUE TITLE
using #documentation for input params fails for nested entities

### ISSUE THREAD

**Issue by nachokb** [ruby-grape/grape-swagger#564]
I've got something like this in some API:

```ruby
# somewhere in PersonAPI
desc 'create a person' do
  params Entities::Person.documentation
end
post do
  ...
end

# entities/person.rb
...
expose :name,
  documentation: {
    type: String,
  }
expose :favorite_cat,
  using: Entities::Cat,
  documentation: {
    type: ::Cat,
    required: true
  }
...
```

Please notice that the `Person` entity has a `#favorite_cat` using _another entity_. That breaks the generated form. Without that `expose`, it generates fields for each attribute (in this case, only `name`); but if I add an `expose ... using` then all I see is a text field for the whole glob.

Isn't this a bug?

**Comment by LeFnord** [comment]
@nachokb … can you provide the related swagger parts for better understanding what you mean

**Comment by LeFnord** [comment]
@nachokb … for nested entities, the type also be the entity …
in your case:
```ruby
expose :favorite_cat,
        using: Entities::Cat,
        documentation: { type: Entities::Cat }
```
