### ISSUE TITLE
Nested resources - doc uses parent entity

### ISSUE THREAD

**Issue by mxmCherry** [ruby-grape/grape-swagger#571]
I have 2 controllers:

```
class API::Entities < API::Base

  # /api/v1/entities/:id , proved to work as expected (rspec tests)
  desc 'Get entity data' do
    success Entity
  end
  get '/entities/:id' do
    @object = ...
    present @object, with: Entity
  end

end
```

```
class API::NestedEntities < API::Base
  resource :entities do
    params do
      requires :entity_id, type: Integer
    end
    route_param :nested_id do
      resource :nested do

        # /api/v1/entities/:id/nested , proved to work as expected (rspec tests)
        desc 'List nested entities for entity' do
          success Entity::Nested
        end
        get '/' do
          @nested_entities = ...
          present @nested_entities, with: Entity::Nested
        end

      end
    end
  end
end
```

This results in doc like (as shown in swagger UI):

> `GET /api/v1/entities/{entity_id}/nested`
> Model: doc for `Entity` is shown there, not `Entity::Nested`

Relevant Gemfile section:

```
gem 'grape', '0.19.1'
gem 'grape-entity', '0.6.0'
gem 'grape-swagger', '0.26.0'
gem 'grape-swagger-entity', '0.1.5'
```

Probably, I'm misusing something?

**Comment by LeFnord** [comment]
@mxmCherry … I don't know if you missing something, cause it isn't really clear what you want achieve, what should be the issue …

so for better understanding, please provide a spec

your first resource, would be correct interpreted as this oapi route: `/api/v1/entities/{id}`
your second (adaptedit a bit)
```ruby
module Api
  module Endpoints
    class Sibling < Grape::API
      resource :parent do
        params do
          requires :parent_id
        end
        route_param :sibling_id do
          resource :sibling do

            desc 'List sibling entities for entity'
            get
          end
        end
      end
    end
  end
end
```

results in: `/api/v1/parent/{sibling_id}/sibling` and this is also expected

if you want to achieve this one: `/api/v1/parent/{parent_id}/{sibling_id}/sibling` and this is what I guess, you should use a second route param instead of the params block, so that it looks like:

```ruby
module Api
  module Endpoints
    class Sibling < Grape::API
      resource :parent do
        route_param :parent_id do
          route_param :sibling_id do
            resource :sibling do

              desc 'List sibling entities for entity'
              get
            end
          end
        end
      end
    end
  end
end
```

**Comment by mxmCherry** [comment]
Hey,

Thanks for your answer.

> if you want to achieve this one: /api/v1/parent/{parent_id}/{sibling_id}/sibling and this is what I guess, you should use a second route param instead of the params block, so that it looks like: ...

Well, no, I have a route `/api/v1/parent/{parent_id}/siblings` listing sibling entities (`Parent.has_many :siblings`). But the generated swagger JSON says this route responds with `Parent` entity, not `Sibling`.

I'll try to provide spec in 2-3 days, sorry for not doing it when opening this issue.

**Comment by mxmCherry** [comment]
Ok, I figured out what was wrong.

Everything works fine when you have, for example, `Entities::Parent` and `Entities::Parent::Sibling`.

But I have something like `Entities::Parent::ForClient` and `Entities::Parent::ForClient`.

So grape-swagger generated definitions like:

```
"definitions": {
  "ForEmployee": { // not Parent::Sibling::ForEmployee, as I expected
    "type": "object",
    "properties": {
      "parent_prop": {
        "type": "string"
      }
    },
    "description": "List"
  }
}
```

I'm quite new to swagger, but I suppose that's intended, right? So no bug here.

Thanks and sorry for taking your time.

**Comment by LeFnord** [comment]
@mxmCherry no problem, that is only a fix, cause route parameters are not supported at the moment see: https://github.com/ruby-grape/grape-swagger/issues/532
