### ISSUE TITLE
No way to document file response

### ISSUE THREAD

**Issue by james-w** [ruby-grape/grape-swagger#582]
Hi,

The swagger spec allows for documenting a reponse of type: `file`, meaning that it streams
data directly in the response.

I have a grape API where I wish to have such an endpoint, but I can't see a way
to specify this type. If I try and do something like `success File` it tries to parse
`File` as a model and complains there are no registered parsers. Even if I were
to fake a parser there would be no way for that parser to set `type: file`.

Thanks,

James

**Comment by LeFnord** [comment]
@james-w … mmh, see actual no way :(

please can you provide the swagger/oapi snippet/link, to see how it should be, thanks
(it is a kind of documentation)

**Comment by LeFnord** [comment]
solved with https://github.com/ruby-grape/grape-swagger/pull/583

**Comment by james-w** [comment]
Thanks.
