### ISSUE TITLE
path_string.rb mutates the route path

### ISSUE THREAD

**Issue by axfcampos** [ruby-grape/grape-swagger#584]
Hi there,

The `build` method in in the [path_string.rb](https://github.com/ruby-grape/grape-swagger/blob/master/lib/grape-swagger/doc_methods/path_string.rb) class mutates the route path forever when generating swagger documentation.

For example:
A path that has a dynamic field:
`/foo/:dynamic/bar`

Is forever changed into:
`/foo/{dynamic}/bar`

This sort of in place mutations can cause weird side effects for the `grape` gem and its dependencies. 

For example, this mutation completely breaks the `grape-route-helpers` gem has it becomes unable to identity [dynamic fields in the path](https://github.com/reprah/grape-route-helpers/blob/master/lib/grape-route-helpers/decorated_route.rb#L122). Using the generated methods to call specific paths no longer works because of it.

I have code that depends on `grape-route-helpers` to generate the paths on the links in a json HAL response. After calling the swagger documentation endpoint, all endpoints start failing on response serialisation.

I tried [changing the code](https://github.com/ruby-grape/grape-swagger/blob/master/lib/grape-swagger/doc_methods/path_string.rb#L6) to copy the path with something like `path = route.path.dup` and it prevents this problem, but it breaks several parts of the code in this gem. Around 68 specs started failing with this change.

I'm a bit lost on finding a fix for this problem, as of now, this is stopping us from using grape-swagger on our live systems. We can only get a static output using a development version.

**Comment by LeFnord** [comment]
@axfcampos … please can you provide a spec to re-produce it, thanks

**Comment by axfcampos** [comment]
Hi @LeFnord 😄 

```ruby
      specify 'The original route path is not mutated' do
        route = Struct.new(:version, :path).new
        route.path = '/foo/:dynamic/bar'
        subject.build(route, add_version: true)
        expect(route.path).to eq '/foo/:dynamic/bar'
      end
```

This was the spec I made to show the route is mutated, [here is the branch](https://github.com/axfcampos/grape-swagger/tree/fix-build-path-mutating-routes).

This specific mutation is this one: https://github.com/ruby-grape/grape-swagger/blob/master/lib/grape-swagger/doc_methods/path_string.rb#L12

**Comment by LeFnord** [comment]
@axfcampos … please can you give https://github.com/ruby-grape/grape-swagger/pull/585 a try

**Comment by axfcampos** [comment]
Thank you so much @LeFnord, just tested and it works now 🙌  🙇

**Comment by LeFnord** [comment]
solved with https://github.com/ruby-grape/grape-swagger/pull/585
