### ISSUE TITLE
SystemStackError: Stack level too deep error when exposing entities

### ISSUE THREAD

**Issue by HowHai** [ruby-grape/grape-swagger#604]
I am getting a stack level too deep when I expose entities that references one another. Is it not possible to expose entity in this matter? My project have many cases where we allow the client to expose associated objects.

```ruby
module API
  module Entities
    class Client < Grape::Entity
      expose :addresses, using: Entities::Address,
        documentation: { type: 'Entities::Address', desc: 'Addresses.', param_type: 'body', is_array: true }
    end

    class Address < Grape::Entity
      expose :client, using: Entities::Client,
        documentation: { type: 'Entities::Client', desc: 'Client' }
    end
  end
end
```

**Comment by Bugagazavr** [comment]
can you show full backtrace?

**Comment by LeFnord** [comment]
first: by your design, it is obvious, cause you are referencing from the Client some Addresses and vice versa, when should it be stopped?
second: did you use the newest gems? If I remember right, this was fixed earlier … and a tried to reproduce it, but without any error

**Comment by HowHai** [comment]
I was using version 0.10. Upgrading to the latest fixed the problem. Thanks @Bugagazavr @LeFnord
