### ISSUE TITLE
Support for multiple entities

### ISSUE THREAD

**Issue by joe11051105** [ruby-grape/grape-swagger#632]
I found this issue #217, but I try to use entities is not work.

```ruby
  desc '',
    detail: "",
    is_array: true,
    entities: [API::V2::Entities::EntityA, API::V2::Entities::EntityB]
```

**Comment by LeFnord** [comment]
Hi @joe11051105 … this PR was never mörged, or better I know nothings about it, on the other side it was for the swagegr 1.2 version …

feel free to make a feature PR

**Comment by joe11051105** [comment]
thanks @LeFnord
