### ISSUE TITLE
Attributes 'example' inside Grape Entity doesn't generate anything

### ISSUE THREAD

**Issue by pinkynrg** [ruby-grape/grape-swagger#647]
Attributes 'example' inside Grape Entity doesn't generate anything on swagger. Instead I see "string"  (for string types)and 0 (for integer type).

**Comment by LeFnord** [comment]
mmh, please provide a spec, so we see what can be the problem …
maybe 'string' and 0 is the example …

**Comment by pinkynrg** [comment]
Whenever I add an example field such as 
`expose :disk_percent, documentation: { type: 'Float', desc: "The column disk_percent of the host", example: 23.21}`

It will not be added to returned example value in swagger ui:

**Comment by pinkynrg** [comment]
Rails 5.0.2
grape 1.0.1
grape-entity 0.6.1
grape-swagger 0.27.1
grape-swagger-entity 0.2.0

**Comment by yewton** [comment]
attribute examples support is added in grape-swagger-entity 0.2.2.
https://github.com/ruby-grape/grape-swagger-entity/blob/master/CHANGELOG.md#022-november-3-2017

**Comment by pinkynrg** [comment]
thank you very much!
