### ISSUE TITLE
Note does not appear in swagger-ui

### ISSUE THREAD

**Issue by pinkynrg** [ruby-grape/grape-swagger#648]
I'm writing something like the following:

```
desc 'Create/update a set controller variables', {
    notes: 'this is a note for the api to create/update controller variables'
}
```
Unfortunately I cannot see the note appearing in swagger-ui

Gem versions:
```
Rails 5.0.2
grape 1.0.1
grape-entity 0.6.1
grape-swagger 0.27.1
grape-swagger-entity 0.2.0
```

**Comment by LeFnord** [comment]
see [#specify-endpoint-details](https://github.com/ruby-grape/grape-swagger#specify-endpoint-details-)

**Comment by pinkynrg** [comment]
what about this #example-code
