### ISSUE TITLE
Inherited `entity_name` is not possible

### ISSUE THREAD

**Issue by jweir** [ruby-grape/grape-swagger#659]
What is the reasoning for using `methods(false)` to detect if a model has an `entity_name` method?

https://github.com/ruby-grape/grape-swagger/blob/d6bed9523344115e7786e8161de14af93aa067b9/lib/grape-swagger/doc_methods/data_type.rb#L51

In my case we have several Entity classes of the same type, but in different domains. Eastern::Market, Western::Market, etc.  These all inherit from a base Grape::Entity class with a custom entity_name method to output EasternMarket, or WesternMarket, etc.

After making an upgrade from an older version of grape-swagger this breaks.

**Comment by LeFnord** [comment]
closewd via #794
