### ISSUE TITLE
Remove "hide_format" from README Configuration Example

### ISSUE THREAD

**Issue by jonmchan** [ruby-grape/grape-swagger#660]
I searched through the codebase and can't find any reference of `hide_format` in the latest commits. I looked at the history and it seems like that config option has been removed. We should remove the reference to `hide_format` from the README to prevent useless cruft from ending up on every new install (like it did for mine :wink: ).

**Comment by LeFnord** [comment]
yeap, please feel free to submit a PR which correct this, thanks
