### ISSUE TITLE
Removing duplicate fields

### ISSUE THREAD

**Issue by obduk** [ruby-grape/grape-swagger#661]
Currently if an API endpoint only has a desc (which is fairly common), grape-swagger uses that description for the summary, description, and response description. To me, that seems like duplication, and better would be to not set the summary unless it is specifically defined

Do people agree / disagree and why?

If it was agreed, I would be happy to do the PR, but wanted to check before putting in the effort.

**Comment by LeFnord** [comment]
please have a look here #629 
it seems, there is actual no progress, so feel free to take over the PR

**Comment by obduk** [comment]
Related, but I was referring to the extra fields under paths. Would also be nice to introduce a documentation method to entities as well to be used. In which case I'll make a PR for this first, then have a look at that PR too.
