### ISSUE TITLE
Grape swagger shows operations in reverse order.

### ISSUE THREAD

**Issue by yeonhoyoon** [ruby-grape/grape-swagger#679]
After this [pull request](https://github.com/ruby-grape/grape-swagger/pull/631) has been merged,
grape swagger shows operations in reverse order from the order they were defined.
I think it makes browsing the documentation a bit more unnatural.

The test case that was provided in the above PR was a case where two apis were defined for same route, which I think is better served by using a versioning strategy.

**Comment by LeFnord** [comment]
@adie what did you think?

to both, please discusse it and find a solution …

for me, it is all the same

**Comment by dchandekstark** [comment]
I agree that this behavior is not expected, since Grape routes are defined in order.
