### ISSUE TITLE
Release 0.31.2

### ISSUE THREAD

**Issue by myxoh** [ruby-grape/grape-swagger#727]
Pending https://github.com/ruby-grape/grape-swagger/pull/726 I think we are ready to generate the next release of grape-swagger.

If no one objects once the PR is merged, I'll go for it.

I'll keep this open for 1 day to give people some time to raise issues

**Comment by LeFnord** [comment]
will have a look on it

**Comment by LeFnord** [comment]
done, will prepare the next release … thans for the hint 😉
