### ISSUE TITLE
Question about documentation for BigDecimal

### ISSUE THREAD

**Issue by dnguyenchevy** [ruby-grape/grape-swagger#753]
What was the decision behind documenting **BigDecimal** datatype as a _double_ and not as _BigDecimal_?

Refer: https://github.com/ruby-grape/grape-swagger/blob/c00c5b40c5ab809047aa40bc36dcd9b871ad24ef/lib/grape-swagger/doc_methods/data_type.rb#L21-L22

**Comment by dnguyenchevy** [comment]
Is this due to swagger limitation with data type?

https://swagger.io/docs/specification/data-models/data-types/#numbers

**Comment by LeFnord** [comment]
yeap, that's the reason for → [OAPI Data Types](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types), cause most other languages – possible consumers of the API – don't have a BigDecimal data type.
