### ISSUE TITLE
Documentation for field with multiple type options

### ISSUE THREAD

**Issue by wedgex** [ruby-grape/grape-swagger#759]
Is there a way to expose a field and document it's type as being one of several options?

For example if I had a `subscriber` field that could either be a `Person` or `Organization` I'd like to be able to express something like

```ruby
expose :subscriber, documentation: { types: [PersonEntity, OrganizationEntity] }
```

**Comment by Bugagazavr** [comment]
Hello, looks like you need `oneOf`, `anyOf` expressions from OAS3, but swagger 2.0 spec doesn't support this.

So, when grape-swagger got OAS3 spec support, this will be possible to implement this for https://github.com/ruby-grape/grape-swagger-entity

**Comment by LeFnord** [comment]
or have a look on the [oapi-3](https://github.com/ruby-grape/grape-swagger/tree/oapi-3) and give it a try
