### ISSUE TITLE
A list of entities is not shown in swagger doc

### ISSUE THREAD

**Issue by charger** [ruby-grape/grape-swagger#770]
1. I use:
```
grape-swagger (0.33.0)
grape-swagger-rails (0.3.1)
```

2. Step to reproduce:
According to documentation I do:
```
add_swagger_documentation \
   models: [
     TheApi::Entities::Location
   ]
```
3. AR:
On `http://localhost:3000/swagger` I don't see the "Model" section. 
4. ER:
 I expected to see the "Model" section beneath the operations list.

When I insert Swagger definition from `http://localhost:3000/api/swagger_doc` into `https://editor.swagger.io/` I see "Model" section, so this problem should relate not to api definition but to Swagger UI bundled into the gem.

**Comment by LeFnord** [comment]
yeap, can be, but didn't know that swagger ui is bundled here 😉

**Comment by charger** [comment]
You are right, this issue related to gem `grape-swagger-rails`. I was lost in a bunch of new gems.
