### ISSUE TITLE
Incomplete entity name for swagger documentation

### ISSUE THREAD

**Issue by mrexox** [ruby-grape/grape-swagger#779]
I've met a problem with swagger documentation because of this method, that parses model name and leaves the last exact entity name (if it is nested). It might be a problem for the case I am going to describe.

https://github.com/ruby-grape/grape-swagger/blob/7237ef3525f907b82b1b4be8d81269d3602af7d0/lib/grape-swagger/endpoint.rb#L335-L337

For my project I use this versioning approach:

```ruby
module API
  module SomeModel
    class V1 < Grape::Entity
      ...
    end
    
    class V2 < Grape::Entity
      ...
    end
  end
end
```

So, for that case parsing of a  model to model name returns just `"V1"` or `"V2"`. That is why all endpoints that end with `V1` will represent the last parsed endpoint.

Could the parsed model name be widened to all the described entity name?

**Comment by LeFnord** [comment]
this is always an ongoing discussion 😉 …

but your arguments are the most reasonable for the moment to change to full name

a PR is welcome 😄

**Comment by mrexox** [comment]
@LeFnord , that's it! https://github.com/ruby-grape/grape-swagger/pull/786
