### ISSUE TITLE
Cant define array params use param_type `body`

### ISSUE THREAD

**Issue by oslivan** [ruby-grape/grape-swagger#805]
Below is my code
```ruby
desc do 
  summary 'Example'
end
params do
  optional :words, type: Array[String], desc: 'Some word'， documentation: { param_type: 'body' }
end
post do
  # params[:words]
end
```
Due to only single array params, so swagger's doc didn't generate ref definition, [reference to](https://github.com/ruby-grape/grape-swagger/blob/588579d12a9f6a3937a06922d4e6424a7aab84da/lib/grape-swagger/doc_methods/move_params.rb#L30), I used `Try it out`, found `curl's script` without bring `words`, so my app raised. I just want to submit params like below
```ruby
# expected
{
  words: ['A','B']
}

# actual
[
  'A',
  'B'
]
```
Have any other solution?

**Comment by LeFnord** [comment]
mmh, maybe you can write it as spec and open an PR …

**Comment by oslivan** [comment]
@LeFnord Thanks for attention, I submitted a PR, please [check it](https://github.com/ruby-grape/grape-swagger/pull/806/commits/f788f4332a14b7fa3925e5cdc15bb2e5d8893646).

**Comment by oslivan** [comment]
I find a [PR](https://github.com/ruby-grape/grape-swagger/pull/553), but I don't understand why it is.

**Comment by LeFnord** [comment]
sorry for latency …

commented on your above PR
