### ISSUE TITLE
Customize heading and order

### ISSUE THREAD

**Issue by Melissasat** [ruby-grape/grape-swagger#807]
Hello ! I can't find in the documentation how to customize the heading "Operation about ...".
I would also like to be able to choose the order of the models, by default it is in alphabetical order.
Thank you !

**Comment by LeFnord** [comment]
1. this will be done with the [`detail`](https://github.com/ruby-grape/grape-swagger#specify-endpoint-details-)
2. ordering … mmh, its a JSON, before on grape-swagger side, its a Hash, so how should it be ordered?  
(IMHO it should be done by the documentation consumer (swagger-ui, redoc, etc))
