### ISSUE TITLE
1.4.3 release

### ISSUE THREAD

**Issue by ktopolski** [ruby-grape/grape-swagger#855]
Hello,

Thank you for your amazing work! We started using grape in 2020 and man - is this a breath of fresh RESTful air after working with other ruby frameworks!

I'd like to ask about the 1.4.3 release. It contains an important fix for the swagger docs we'd like to use(#846). I can see that the PR is merged and it's mentioned in the `CHANGELOG` but.. there's no `1.4.3` tag in the repository 🤔 There's also no new release at [rubygems](https://rubygems.org/gems/grape-swagger/versions).

Is there something blocking the `1.4.3` release? 🤔

**Comment by pieterocp** [comment]
Looks [like 1.4.3](https://github.com/ruby-grape/grape-swagger/blob/master/CHANGELOG.md#143-january-5-2022), is out and done, so this issue could be closed.
