### ISSUE TITLE
new release soon ?

### ISSUE THREAD

**Issue by dhruvCW** [ruby-grape/grape-swagger#898]
Grape 1.7.1 release and especially https://github.com/ruby-grape/grape/pull/2323 is not usable with grape swagger. Could a new release be made so that the two gems can be used together ?

**Comment by LeFnord** [comment]
done

besides that you could add to your Gemfile:
```ruby
gem 'grape-swagger-entity', git: 'https://github.com/ruby-grape/grape-swagger'
```
to make use of not yet released versions
