### ISSUE TITLE
Should rack-test be considered an optional dependency?

### ISSUE THREAD

**Issue by x-yuri** [ruby-grape/grape-swagger#908]
I'm running `swagger-ui` in a docker container by [providing it a `swagger.json` file][a]. Which I build with [`rake oapi:fetch`][d]. After switching from `bundle install` to `bundle install --without test development` I realized that `grape-swagger` [needs `rack-test`][c], which is [not in the dependencies][b]. Do you want to add it to the dependencies? Or should I install it manually? Or I'm doing something wrong? On a side note, why does the `rake` task need `rack-test`?

[a]: https://github.com/swagger-api/swagger-ui/blob/v5.9.0/docs/usage/installation.md#docker
[b]: https://rubygems.org/gems/grape-swagger/versions/1.6.1
[c]: https://github.com/ruby-grape/grape-swagger/blob/v1.6.1/lib/grape-swagger/rake/oapi_tasks.rb#L5
[d]: https://github.com/ruby-grape/grape-swagger/blob/v1.6.1/README.md#rake

**Comment by LeFnord** [comment]
yes … please add it to the runtime dependencies in gemspec, it is needed for the [rake tasks](https://github.com/ruby-grape/grape-swagger/blob/master/lib/grape-swagger/rake/oapi_tasks.rb)
