### ISSUE TITLE
Restore Ruby 3.0 support?

### ISSUE THREAD

**Issue by godfat** [ruby-grape/grape-swagger#915]
GitLab attempted to upgrade `grape-swagger` from `1.6.1` to `2.0.0`, however GitLab has to revert it because 2.0.0 doesn't support Ruby 3.0: https://gitlab.com/gitlab-org/quality/engineering-productivity/master-broken-incidents/-/issues/4841#note_1710824588

I noticed this was dropped at https://github.com/ruby-grape/grape-swagger/commit/8e723c6383e40ea47b6a6aad3391e98bbd356cad

And I see the reasoning was:

> * Aligns ruby and grape version with test matrix.

Which makes sense to me. However, I would like to ask if it's possible to at least restore support for Ruby 3.0 if it's actually working. I tried to run tests locally with Ruby 3.0 and everything passed.

**Comment by godfat** [comment]
I created a pull request for consideration: https://github.com/ruby-grape/grape-swagger/pull/916

**Comment by LeFnord** [comment]
closed via #916 

and released as 2.0.1
