### ISSUE TITLE
Version 2.1.0 breaks current swagger docs (2.0.3 works correctly though)

### ISSUE THREAD

**Issue by americos** [ruby-grape/grape-swagger#932]
Hi, we recently updated our grape-swagger version from `2.0.3` to `2.1.0`, but we noticed that in this latest version, our swagger docs look broken, as in not all params are shown (not entirely sure why but `2.0.3` works correctly). 

We went through the code changes and we aren't sure why this appears to be broken.

**Comment by LeFnord** [comment]
what do you mean with it?

**Comment by LeFnord** [comment]
maybe it is related to this issue → #931 ?

**Comment by franckduche** [comment]
Hello,
Basically we went from this:
<img width="873" alt="Capture d’écran 2024-06-11 à 09 02 37" src="https://github.com/ruby-grape/grape-swagger/assets/5946920/10106d22-bae9-44d4-90b1-2cc0eec32ada">
To this:
<img width="959" alt="Capture d’écran 2024-06-11 à 09 03 02" src="https://github.com/ruby-grape/grape-swagger/assets/5946920/2532cdde-0932-4181-aa6a-1cc8d0c49a4b">

**Comment by LeFnord** [comment]
now it looks ok to me, the content type is `application/json` → a body parameter type, not formData,
this was fixed → #927

**Comment by americos** [comment]
Thanks for the reply @LeFnord, I looked at https://github.com/ruby-grape/grape-swagger/pull/927 and saw that there is a `consumes` property, after using that inside my `desc` block it worked as before.

Closing issue, thanks again.
