### ISSUE TITLE
Compatibility with grape 2.2.0

### ISSUE THREAD

**Issue by padde** [ruby-grape/grape-swagger#939]
Running on the latest 2.2.0 release of grape will produce these exceptions:

    NameError:
      uninitialized constant Grape::ContentTypes::CONTENT_TYPES
    # ./lib/grape-swagger/endpoint.rb:15:in `content_types_for'

    NoMethodError:
      undefined method `formatters' for module Grape::Formatter
    # ./lib/grape-swagger/endpoint.rb:14:in `content_types_for'

Used here:
* https://github.com/ruby-grape/grape-swagger/blob/v2.1.0/lib/grape-swagger/doc_methods/produces_consumes.rb#L10
* https://github.com/ruby-grape/grape-swagger/blob/v2.1.0/lib/grape-swagger/endpoint.rb#L15

Grape has removed/renamed these constants/methods via https://github.com/ruby-grape/grape/commit/fb67ea9940ea47d353cc9b413a7e25fc8da0983e#diff-e28e889e3579545f8e2fedc3ab52f78530206ed808afdc9a23703f8b089f80e3

**Comment by padde** [comment]
I'd love to work on a fix, however I am not sure what the correct solution would be here. I'd be grateful for any guidance.

My first idea would be not to rely on internal constant names and instead use the `Grape::ContentTypes.content_types_for` method instead. Any thoughts on this?

**Comment by olivier-thatch** [comment]
We just ran into this after Dependabot upgraded the grape gem.

Unless a fix is going to be released soon, I would recommend releasing a new patch version that updates the gemspec to change the `< 3.0` grape constraint to `< 2.2`.

**Comment by padde** [comment]
So I had started [working on a fix](https://github.com/ruby-grape/grape-swagger/pull/940) for this but apparently it's not as easy to solve as I thought. What I've found so far:

`grape-swagger` references some internal constants and methods of `grape` regarding content types and formatters, which were removed/renamed with its 2.2.0 release.

@dblock [suggested](https://github.com/ruby-grape/grape-swagger/pull/940#pullrequestreview-2308691023) just copying over those constants from grape which I have [done in my PR](https://github.com/ruby-grape/grape-swagger/pull/940) but this should really only be seen as a temporary fix.

I am saying this because from what I understand, referencing these constants was never really giving us the expected result in the first place. Grape allows specifying custom content types and formatters in the DSL, which seem to have been disregarded by `grape-swagger` the whole time. Personally, I would not attempt to fix this in the same PR as we might have to spend a considerable amount of work to come up with a solution that actually works for older and newer grape versions as well as new test cases. I think we should treat this issue as a separate bug.

**Comment by padde** [comment]
I see this issue has already been reported a few years ago, for reference: https://github.com/ruby-grape/grape-swagger/issues/700

**Comment by dblock** [comment]
@padde You're absolutely right. Fixing #700 is beyond the basic compat scope, so let's keep it that way. Thanks for picking the simple fix up.

**Comment by dblock** [comment]
I released 2.1.1.
