### ISSUE TITLE
Grape::ContentTypes::CONTENT_TYPES is not available anymore.

### ISSUE THREAD

**Issue by khallaghi** [ruby-grape/grape-swagger#941]
Hi everyone,
While reviewing the `ProducesConsumes` class, I came across a reference to `Grape::ContentTypes::CONTENT_TYPES`. In the newer version of Grape, this has been replaced by `Grape::ContentTypes::DEFAULTS`, as highlighted in the diff below:
[Diff of lib/grape/content_types.rb](https://github.com/ruby-grape/grape/commit/fb67ea9940ea47d353cc9b413a7e25fc8da0983e#diff-e28e889e3579545f8e2fedc3ab52f78530206ed808afdc9a23703f8b089f80e3L7)
Additionally, here is the faulty code that caused our workflows to break:
https://github.com/ruby-grape/grape-swagger/blob/a5e2575a02e42bd62c33735a605cdee630ec30ad/lib/grape-swagger/doc_methods/produces_consumes.rb#L10

**Comment by dblock** [comment]
Resolved in https://github.com/ruby-grape/grape-swagger/pull/940.

**Comment by dblock** [comment]
I released 2.1.1.
